### ISSUE TITLE
Removes references to excess.org

### ISSUE THREAD

**Issue by uSpike** [urwid/urwid#108]
When trying to install urwid via easy_install, i'm getting:

```
Searching for urwid==1.3.0
Reading https://pypi.python.org/simple/urwid/
Reading http://excess.org/urwid/
error: [Errno 104] Connection reset by peer
```

It is an intermittent problem.  Ususally running the install script again will work.

**Comment by techtonik** [comment]
is `easy_install` still supported?

**Comment by wardi** [comment]
I thought we removed these references. What else do we need to change?

**Comment by techtonik** [comment]
I guess nothing.

**Comment by vapier** [comment]
close old report ?
