### ISSUE TITLE
SelectableIcon should focus first character by default

### ISSUE THREAD

**Issue by wernight** [urwid/urwid#115]
`SelectableIcon` widget is current having `cursor_position = 1` by default which would result in:

```
S[o]mething
```

with the cursor on `o`.

Commonly the cursor is either at be first character (0) or at the end of the line. I'd suggest to make this default either 0 or -1 and support -1 for last character.

**Comment by wardi** [comment]
Sure, submit a PR.

**Comment by wernight** [comment]
Here it is...

**Comment by wernight** [comment]
bump

**Comment by and3rson** [comment]
@wernight Thanks! Going to merge it.
