### ISSUE TITLE
Some Urwid examples cannot work in python3

### ISSUE THREAD

**Issue by whospal** [urwid/urwid#129]
Hi,

I tried some of the examples with python 3 but encountered exceptions.
Here are the list that can't work with python3:
1) calc.py
2) graph.py
3) fib.py
4) browse.py
5) dialog.py

**Comment by hkoof** [comment]
Urwid installed for python2 is not compatible with urwid installed for python3. Did you use an urwid installed by/for python2 to try those examples? That could be the cause. The source package is the same for 2 and 3, but it is determined at set-up time for which python version urwid will work.

**Comment by whospal** [comment]
Yes, I used the source, and specify for python3. Hence, tour.py works. Just highlighting that not all the examples are upgraded to python3, which some people may assume so. 


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Heiko <notifications@github.com> </div><div>Date:02/07/2015  19:41  (GMT+08:00) </div><div>To: wardi/urwid <urwid@noreply.github.com> </div><div>Cc: whospal <andrewgohlk@yahoo.com> </div><div>Subject: Re: [urwid] Some Urwid examples cannot work in python3 (#129) </div><div>
</div>Urwid installed for python2 is not compatible with urwid installed for python3. Did you use an urwid installed by/for python2 to try those examples? That could be the cause. The source package is the same for 2 and 3, but it is determined at set-up time for which python version urwid will work.

**Comment by wardi** [comment]
The examples need to be run through 2to3 at the moment. If you'd like to help make them source compatible that would be much appreciated!

**Comment by eevee** [comment]
There's been a lot of dual-mode porting work in the last couple years, and all five of those examples work with Python 3.7 for me, with a fresh checkout.
