### ISSUE TITLE
AsyncioEventLoop test failure with Python 3.4 on arm* CPU

### ISSUE THREAD

**Issue by rhertzog** [urwid/urwid#145]
Version 1.3.0 of urwid failed its test suite with Python 3.4 during build of the Debian package on armhf and armel architectures.

Here's the failing test:

```
FAIL: test_run (urwid.tests.test_event_loops.AsyncioEventLoopTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "«PKGBUILDDIR»/build/lib.linux-armv7l-3.4/urwid/tests/test_event_loops.py", line 64, in test_r
un
    self.assertEqual(out, ["clean exit"])
AssertionError: Lists differ: ['waiting', 'clean exit'] != ['clean exit']

First differing element 0:
waiting
clean exit

First list contains 1 additional elements.
First extra element 1:
clean exit

- ['waiting', 'clean exit']
+ ['clean exit']
```

The build on i386/amd64 is not affected. Let me know if you want me to try out some patches.

**Comment by wardi** [comment]
I'm happy to try out some patches!  The Debian ARM builds have had failing event loop tests for quite some time now.

**Comment by penguinolog** [comment]
Python 3.4 is reached EOL and fixes for it are not expected.
Closing issue.
