### ISSUE TITLE
Threading Support

### ISSUE THREAD

**Issue by chrisspen** [urwid/urwid#165]
Is Urwid thread safe? I'd like to have a thread update widgets asynchronously, regardless of user input, but I can't find this mentioned in the docs anywhere.

Btw, I wanted to ask this question the mailing list, but it appears to be down. I can't subscribe to it, and no one appears to have posted to it since March.

**Comment by wardi** [comment]
No, you can't safely update the widgets from another thread while the main thread is drawing them.
You can use something like watch_pipe in the https://github.com/wardi/urwid/blob/master/examples/subproc.py example to wake the main thread for updates. Or if you're just responding to I/O or timers  make your code event driven instead and not bother with threads.

The mailing list is down, I need to set up a new one. Thanks for the reminder.

**Comment by chrisspen** [comment]
What's the danger of using threads? I just wrote a simple example that changes some text once a second, alongside a menu, and it seems to work just fine.

**Comment by eevee** [comment]
"It seems to work just fine" are famous last words  :)  Imagine what would happen if you changed the text in two widgets from a thread, and the main thread decided to do an update _between_ those changes.

**Comment by chrisspen** [comment]
My thread calls MainLoop.draw_screen(), so overriding that to use a lock, and then using that lock in my thread to update the widgets, seems to prevent any possible race conditions and effectively make Urwid thread safe.

    import urwid, threading, time

    DRAW_LOCK = threading.RLock()

    class MainLoop(urwid.MainLoop):
        
        def draw_screen(self, *args, **kwargs):
            with DRAW_LOCK:
                super(MainLoop, self).draw_screen(*args, **kwargs)

    def my_thread():
        counter = 0
        while 1:
            counter += 1
            with DRAW_LOCK:
                some_widget.set_text(str(counter))
                loop.draw_screen()
            time.sleep(1)

**Comment by TomasTomecek** [comment]
this may happen:

```
Traceback (most recent call last):
  File "/home/me/sen/tui/init.py", line 155, in run
    loop.run()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 277, in run
    self._run()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 374, in _run
    self.event_loop.run()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 677, in run
    self._loop()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 705, in _loop
    self._entering_idle()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 666, in _entering_idle
    callback()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 559, in entering_idle
    self.draw_screen()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 573, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib64/python3.5/site-packages/urwid/widget.py", line 140, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.5/site-packages/urwid/decoration.py", line 224, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib64/python3.5/site-packages/urwid/widget.py", line 140, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.5/site-packages/urwid/container.py", line 1095, in render
    assert foot.rows() == frows, "rows, render mismatch"
AssertionError: rows, render mismatch
```

**Comment by freisei** [comment]
> 
> 
> My thread calls MainLoop.draw_screen(), so overriding that to use a lock, and then using that lock in my thread to update the widgets, seems to prevent any possible race conditions and effectively make Urwid thread safe.
> 
> ```
> import urwid, threading, time
> 
> DRAW_LOCK = threading.RLock()
> 
> class MainLoop(urwid.MainLoop):
> 
>     def draw_screen(self, *args, **kwargs):
>         with DRAW_LOCK:
>             super(MainLoop, self).draw_screen(*args, **kwargs)
> 
> def my_thread():
>     counter = 0
>     while 1:
>         counter += 1
>         with DRAW_LOCK:
>             some_widget.set_text(str(counter))
>             loop.draw_screen()
>         time.sleep(1)
> ```
Hello,

i tried to implement your code in a python-file.

`import urwid, threading, time

DRAW_LOCK = threading.RLock()

class MainLoop(urwid.MainLoop):

	def draw_screen(self, *args, **kwargs):
		with DRAW_LOCK:
			super(MainLoop, self).draw_screen(*args, **kwargs)

def my_thread():
	time.sleep(0.5)
	global loop, text;
	counter = 0
	while 1:
		counter += 1
		with DRAW_LOCK:
			text.set_text(str(counter))
			loop.draw_screen()
		time.sleep(1)

		

text = urwid.Text("Hello World")
filler = urwid.Filler(text)
loop = MainLoop(filler)
print ("this is mainthread")
		
thread1 = my_thread()
thread1.start()
loop.run()`

Result is

`root@eipi:~# python urwidthread1.py
this is mainthread
Traceback (most recent call last):
  File "urwidthread1.py", line 30, in <module>
    thread1 = my_thread()
  File "urwidthread1.py", line 19, in my_thread
    loop.draw_screen()
  File "urwidthread1.py", line 9, in draw_screen
    super(MainLoop, self).draw_screen(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 579, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 670, in draw_screen
    assert self._started
AssertionError`

Whats wrong?

**Comment by ulidtko** [comment]
I don't think anyone should even spend effort on this and *try to make* Urwid thread-safe. It's a lost cause.

As Ian said: do it event-driven. Use a channel. Use a pipe. If you're advanced enough to confidently say you've set all your locks correctly — you should have no problem with message-passing as well. Otherwise — needing to mutate GUI from multiple threads is a sure symptom that you're doing it wrong.

Worse yet; there's no way Urwid could specify, implement, test and maintain such support. We're having [way too much fun](/urwid/urwid/issues) in just a single thread; now you're asking us to multiply that by non-determinism. No thanks.

**Comment by dejlek** [comment]
So how do you run (potentially) blocking operation? It will stop the main loop, and render the whole UI unresponsive, right? I am trying to find example how people implemented say DB query execution that does not block the whole application...

**Comment by tonycpsu** [comment]
@dejlek : Using asyncio, twisted, or another run loop lets you do blocking IO and such in coroutines.

**Comment by dejlek** [comment]
So you run both urwid and twisted/asyncio loop in your apps?

**Comment by tonycpsu** [comment]
[Indeed it would](https://github.com/urwid/urwid/blob/master/examples/asyncio_socket_server.py)!

**Comment by pcenshao** [comment]
> No, you can't safely update the widgets from another thread while the main thread is drawing them. You can use something like watch_pipe in the https://github.com/wardi/urwid/blob/master/examples/subproc.py example to wake the main thread for updates. Or if you're just responding to I/O or timers make your code event driven instead and not bother with threads.
> 
> The mailing list is down, I need to set up a new one. Thanks for the reminder.



Can I use `set_alarm_in(sec, callback, user_data=None)` to impl same effect?

Use this method like:
`
def cb(a,b):
    widget.set_text('updated')

main_loop.set_alarm_in(0,cb)
`

urwid offical doc:
<dt id="urwid.MainLoop.set_alarm_in" style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="descname" style="background-color: transparent; padding: 0px 1px; font-size: 1.2em; font-weight: bold;">set_alarm_in</code><span class="sig-paren" style="font-size: larger;">(</span><em>sec</em>,<span> </span><em>callback</em>,<span> </span><em>user_data=None</em><span class="sig-paren" style="font-size: larger;">)</span><a class="headerlink" href="https://urwid.readthedocs.io/en/latest/reference/main_loop.html#urwid.MainLoop.set_alarm_in" title="Permalink to this definition" style="color: rgb(24, 16, 53); text-decoration: none; visibility: hidden; font-size: 0.8em; padding: 0px 4px;"></a></dt><dd style="margin-top: 3px; margin-bottom: 10px; margin-left: 30px; text-align: justify; line-height: 20.8px; color: rgb(0, 0, 0); font-family: sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="margin-top: 0px; text-align: justify; line-height: 20.8px;">Schedule an alarm in<span> </span><em>sec</em><span> </span>seconds that will call<span> </span><em>callback</em><span> </span>from the within the<span> </span><a class="reference internal" href="https://urwid.readthedocs.io/en/latest/reference/main_loop.html#urwid.MainLoop.run" title="urwid.MainLoop.run" style="color: rgb(38, 49, 147); text-decoration: none;"><code class="xref py py-meth docutils literal" style="background-color: transparent; padding: 0px 1px; font-size: 0.95em; font-weight: bold;"><span class="pre">run()</span></code></a><span> </span>method.</p>
Parameters: | sec (float) – seconds until alarmcallback (callable) – function to call with two parameters: this main loop object and user_data
-- | --


</dd>set_alarm_in(sec, callback, user_data=None)
Schedule an alarm in sec seconds that will call callback from the within the [run()](https://urwid.readthedocs.io/en/latest/reference/main_loop.html#urwid.MainLoop.run) method.

Parameters:	
sec (float) – seconds until alarm
callback (callable) – function to call with two parameters: this main loop object and user_data

link: https://urwid.readthedocs.io/en/latest/reference/main_loop.html

**Comment by pcenshao** [comment]
I had use MainLoop.watch_pipe() to resolve this problem.
`
in main thread:
main_loop = urwid.MainLoop(top, palette)
    ui_update_pipe = main_loop.watch_pipe(update_ui)
    main_loop.run()

    def update_ui(data):
        """
        在MainLoop中被调用，执行更新UI的工作
        :param data:
        :return:
        """
        program_status_ctrl.set_text(program_status_text_prefix + Ui_Info["progress_view"])
        handle_info_ctrl.set_text(handle_info_text_prefix + Ui_Info["handle_info"])
        pass

`

`
in business thread

    def notify_update_ui():
        """
        在处理Excel文件中线程中调用，以通知MainLoop更新UI
        :return:
        """
        if ui_update_pipe != -1:
            os.write(ui_update_pipe,b"notify_update_ui")

`

the "ui_update_pipe" is the value of MainLoop.watch_pipe () returned
