### ISSUE TITLE
SelectEventLoop may never wake up for an alarm 

### ISSUE THREAD

**Issue by kesipyc** [urwid/urwid#179]
If no alarm was set - main loop will wait for some fd to be ready: main_loop.py(706):
`ready, w, err = select.select(fds, [], fds)`

If one alarm for far away future is set - timeout with high value will be used: main_loop.py(703)
`ready, w, err = select.select(fds, [], fds, timeout)`

In both cases adding new alarm in close future (like 1 second) will not make main loop waking up anywhere close to 1 second... If you are unlucky with no fd event coming you can wait for arbitrarily long until callback is fired.

I think there should be some flag/fd/something that will manually wake main loop whenever new alarm is added so it can recalculate new timeout.

**Comment by wardi** [comment]
This sounds like you're calling set_alarm_in from a different thread. That's not a safe thing to do. Instead use watch_pipe to get a pipe you can use from your thread to trigger code that accesses the urwid widgets or timers.

**Comment by kesipyc** [comment]
Oh ok. You are right about different thread. I want to update widget data from this other thread.
I don't want to use watch_pipe because my data is python list and I don't want overhead of converting it into binary and back into list. I can guarantee that after creating, my data is immutable (not changed by any thread)

**Comment by wardi** [comment]
You should be able to send one character down the pipe just as a signal, then access your list from the urwid thread, then
