### ISSUE TITLE
offere mail-adress to google-groups

### ISSUE THREAD

**Issue by buhtz** [urwid/urwid#181]
Your link to the google-groups is quite complex
https://groups.google.com/a/excess.org/d/forum/urwid

I tried some combinations but this doesn't work.

Normaly I it is very easy to create mail-adress out of it.
e.g. https://groups.google.com/group/sqlalchemy becomes sqlalchemy@googlegroups.com with the corrosponding sqlalchemy+unsubscribe@googlegroups.com and sqlalchemy+subscribe@googlegroups.com

**Comment by wardi** [comment]
closing as duplicate of #180
