### ISSUE TITLE
Building TextCanvas with existing text, attr and cs splits on bytes, not characters

### ISSUE THREAD

**Issue by pquentin** [urwid/urwid#182]
(I've cross-posted this issue at https://github.com/inducer/pudb/issues/172)

I'm using the pudb debugger in Python 3. The variables are displayed in a `urwid.TextCanvas` that you can see on the right of this screenshot:

![pudb](https://asmeurersympy.files.wordpress.com/2011/08/screen-shot-2011-08-07-at-8-28-11-pm.png)

pudb uses `TextCanvas` after having wrapped the lines himself, which is why it prepares `text`, `attr` and `cs` himself. Unfortunately, TextCanvas somehow wraps the lines again, but it wrap bytes, not an unicode string. As a result, Unicode codepoints that are encoded using two bytes in UTF-8 can be split in two. The code below reproduces the issue:

```
from urwid import TextCanvas

text=u'aaaaaé'
cols=len(text)

c = TextCanvas(
    text=[text.encode('UTF-8')],
    attr=[[('var value', cols)]],
    cs=[[(None, cols)]],
    maxcol=cols
)

print(list(c.content()))
```

It prints `[[('var value', None, b'aaaaa\xc3'), (None, None, b'\xa9')]]` while I would have expected `[[('var value', None, b'aaaaa\xc3\xa9')]]`

pudb crashes nearly every day due to this bug. Is pudb using urwid incorrectly, or is this a urwid bug? Thank you!

**Comment by wardi** [comment]
I'm pretty sure attr is (attribute, number_of_bytes) tuples not (attribute, columns) because Canvases are just dealing with bytes. You can check what rendering a Text widget produces to verify.

**Comment by pquentin** [comment]
Sending bytes works. Closing this in favor of the pudb issue. Thank you @wardi!
