### ISSUE TITLE
BUG: raw_display: hook_event_loop does not memoize handles

### ISSUE THREAD

**Issue by aleufroy** [urwid/urwid#221]
I created an application on top of urwid (https://bitbucket.org/aleufroy/lairucrem) which sometime interrupts the main loop to spawn an EDITOR process.

The editor process crashes because `raw_display.Screen.unhook_event_loop` do not "release" the stdout/stdin.

The real issue is introduced by `raw_display.Screen.hook_event_loop` which doesn't save the handles into `self._current_event_loop_handles`.

**Comment by and3rson** [comment]
Waiting on update of #222 for this.
