### ISSUE TITLE
Travis CI breaking in 2.7 - Twisted/OpenSSL error

### ISSUE THREAD

**Issue by ocarneiro** [urwid/urwid#223]
Travis CI broke when running python 2.7:
https://travis-ci.org/urwid/urwid/jobs/211680458

Tried to reproduce it in my machine (Debian Stretch RC2), but didn't succeed. All 280 tests passed.

Found the source code where the error happens. Thought it could help:
https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/_sslverify.py

I guess it is some OpenSSL version incompatibility in the Travis server, maybe? It's strange that it broke only on 2.7...

I'd love to help more, but I don't know enough to do so (yet!).

Urwid is great, by the way. Thanks for all the effort!

**Comment by wardi** [comment]
we might need a workaround for the tests like this one https://github.com/urwid/urwid/blob/master/.travis.yml#L15

**Comment by ocarneiro** [comment]
Perhaps the calls to twisted should be mocked in the tests? 
I'm thinking about something like this: https://blog.fugue.co/2016-02-11-python-mocking-101.html

**Comment by wardi** [comment]
sure, I'd support that if someone wanted to do the work.

I bet pinning some versions for the tests will be easier, though :-)

**Comment by and3rson** [comment]
It seems like this no longer takes place in recent builds. Considering this as fixed.
