### ISSUE TITLE
How to make any widget scrollable?

### ISSUE THREAD

**Issue by rndusr** [urwid/urwid#226]
I have a bunch of fixed, multi-line, non-focusable widgets combined in a
GridfFlow, and the resulting canvas is larger than any reasonably sized
terminal. Is there any way I can scroll the whole canvas up and down?

If not, I was thinking that it would be nice to have a `Scrollable` widget that
wraps another widget. It would implement a `keypress` method that catches the
keys `up` and `down`, keeps track of the scrolling position and a `render`
method that renders the whole wrapped widget and extracts the part of the canvas
at the current scroll position.

That would make it possible to scroll through arbitrarily complex widgets line
by line. Eventually, it could also implement vertical scrolling and scroll bars.

Is that a good approach or is there a better way to do it?

**Comment by rndusr** [comment]
I went ahead and implemented a `Scrollable` and a `ScrollBar` class:
https://github.com/rndusr/stig/blob/dev/stig/tui/scroll.py

The behaviour when changing focus inside a `Scrollable` can be a little
unexpected, depending on the layout, but it should be possible to fix
that. Otherwise it works quite well for me.

I'd be happy to make adjustments and eventually submit a pull request if there
is interest.

**Comment by xird** [comment]
I could definitely use this. Could you provide examples on how to use these for a urwid newbie?

**Comment by rndusr** [comment]
`Scrollable` and `ScrollBar` just wrap around other widgets. Scrollable should just work with any fixed or flow widget.

Widgets supplied to ScrollBar need the non-standard methods `rows_max` (returns maximum/total number of rows for a given size) and `get_scrollpos` (returns current scroll position). `Scrollable` provides these methods.

Here is a very simple example:

```python
text1 = '''
Not
a
very
long
Text.
'''

text2 = '''
Another
not
very
long
Text.
'''

main = urwid.Pile([('pack', urwid.Text(text1)),
                   ('pack', urwid.Text(text2))])
mainloop = urwid.MainLoop(ScrollBar(Scrollable(main)))
mainloop.run()
```

You can also have a look at the tests:
https://github.com/rndusr/stig/blob/dev/tests/tui_test/scroll_test.py

If you want to add a ScrollBar to a ListBox, you have to monkey patch the ListBox class like this:
https://github.com/rndusr/stig/blob/dev/stig/tui/urwidpatches.py#L124

Then you should be able to do `ScrollBar(PatchedListBox(...))`.

Have fun! :)

**Comment by xird** [comment]
Thanks! This should get me on the right track.

**Comment by xird** [comment]
The links in your earlier comments were broken, but I did find the code from https://github.com/rndusr/stig/blob/master/stig/tui/scroll.py

There were a couple of fixes I needed to do before the scrollbar worked correctly. You may want to upstream these:

```
253c253
<     def __init__(self, widget, thumb_char='\u2588', trough_char=' ',
---
>     def __init__(self, widget, thumb_char=u'\u2588', trough_char=' ',
303c303
<         top_weight = pos / max(1, posmax)
---
>         top_weight = float(pos) / max(1, posmax)
304a305
>
```

Thanks again!

**Comment by rndusr** [comment]
That's because I'm using it in a python3-only project and didn't notice the lacking python2 compatibility.

I fixed it anyway in case others want to use it. Thanks for the note.

**Comment by kpj** [comment]
I also find this functionality very useful.
As indicated [here](https://github.com/rndusr/stig/issues/53#issuecomment-367365660), it seems mostly ready except for some missing optimizations (although it is unclear how easily implemented those are).

I would suggest to start with a PR for `Scrollable` and `ScrollBar`, in order to continue with explicit code.
What do you think?

**Comment by kiwiz** [comment]
Hi there, I'm interested in this functionality as well. @rndusr anything I can do to help here?

**Comment by rndusr** [comment]
Thanks for the offer. I don't see an easy way the remaining issues can be
resolved without redesigning some parts of urwid. But I'd be willing to keep
working on this and make a PR if anyone finds a solution.

One issue is figuring out if the widget we want to make scrollable should get a
keypress.
https://github.com/rndusr/stig/blob/master/stig/tui/scroll.py#L112

Another issue is moving the cursor when making a container with multiple Edit
widgets scrollable. An Edit can also have multiple lines.
https://github.com/rndusr/stig/blob/master/stig/tui/scroll.py#L37

I wish I would've kept my experiment setup so I could provide some code that
demonstrates the issues more clearly.

**Comment by kiwiz** [comment]
Just tossing out ideas:
- For the former, what if the render method accepted an offset `(x, y)` tuple? I don't think that can be done in a backwards-compatible way, though...
- For the latter, could we patch the Edits to return the keystroke if no action can be taken? (Ex: Return "up" if the cursor is already at line 0 of the Edit)

**Comment by rndusr** [comment]
To be honest, I don't remember the details.

I'll try to find some time this week to make new demos.

**Comment by rndusr** [comment]
Here's the demo code for the keypress issue:
https://gist.github.com/rndusr/7e139a5709a44db2debc4d1702c53444

**Comment by rndusr** [comment]
Here's the demo for the other known issue:
https://gist.github.com/rndusr/10f11864ff1b8d62907cf9a5abdff418

It's not a real dealbreaker, but this behaviour can be really unintuitive in my
opinion.

**Comment by rr-** [comment]
@rndusr 
Your `ScrollBar` looks fantastic and I'm looking into using it in https://github.com/rr-/pq-cli.git, however it seems there is a problem when you combine it with `urwid.Overlay`:

```
import random

import urwid

from scroll import Scrollable, ScrollBar


texts = [
    """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.""",
    "test",
]


def linebox():
    return urwid.LineBox(
        ScrollBar(
            Scrollable(
                urwid.Pile(
                    [
                        urwid.Columns(
                            [
                                urwid.Text(random.choice(texts)),
                                urwid.Text(random.choice(texts)),
                            ]
                        )
                        for _ in range(25)
                    ]
                )
            )
        )
    )


columns = urwid.Columns(
    [
        ("weight", 1, urwid.Pile([linebox(), linebox()])),
        ("weight", 2, urwid.Filler(urwid.Text("derp"))),
    ]
)


def unhandled_keypress(key):
    if key == "ctrl x":
        raise urwid.ExitMainLoop()


widget = urwid.Pile([columns, (1, urwid.Filler(urwid.Text("derp")))])
loop = urwid.MainLoop(widget, unhandled_input=unhandled_keypress)
loop.widget = urwid.Overlay(
    urwid.LineBox(urwid.Filler(urwid.Text("herp"))),
    loop.widget,
    "center",
    10,
    "middle",
    10,
)
loop.run()
```

I get either `cviews do not fill gaps in shard_tail!` or `cviews overflow gaps in shard_tail!`. I'm not currently sure if it's bug in urwid, or the `ScrollBar` implementation.

**Comment by rndusr** [comment]
It's probably a bug in my implementation. It's kind of hacked into urwid. As
mentioned earlier, there are other issues, too.

I'm not very motivated to look into this as the maintainer doesn't seem
interested in a PR. But if you find a solution, feel free to make a PR in stig.

**Comment by Atem18** [comment]
Hi @rndusr , what do you recommand to do when using : http://urwid.org/tutorial/index.html#horizontal-menu, to display urwid.Text([u'  You chose ', self.caption, u'\n']) taking as much as space as possible of the screen and scrollable ?

Thanks a lot in advance

**Comment by rndusr** [comment]
I don't understand you question.

Firstly, from the screenshots it looks like it already does take as much screen
space as the menu.

Secondly, what do you want to scroll? "You chose Idle" fits in a one-line
terminal, and even then there is nothing to scroll.

Maybe you can post mockup screenshots to show what you want?

**Comment by Atem18** [comment]
@rndusr The box size is 10x24. I changed it to 80x24, so it's ok when browsing the menu but when I select an item, I want to display a text (or a log file) scrollable in full size.

How to achieve that ?

Mockup for reference: https://s3.amazonaws.com/assets.mockflow.com/app/wireframepro/company/C88ac345e101c4bd481d46a50faad3b3e/projects/M3f341fbb2161da52621d9f5b32fb72c31562138537608/pages/f3c80246efda4eae819a3a8cbeea4ccd/image/f3c80246efda4eae819a3a8cbeea4ccd.png

**Comment by rndusr** [comment]
Should be as simple as this:

    urwid.ScrollBar(urwid.Text(...))

I'm not sure if you need to wrap the ScrollBar into a Frame or something if
you're want it to be the top-level widget. I never got the hang of urwid's
sizing modes: http://urwid.org/manual/widgets.html#box-flow-and-fixed-widgets

**Comment by Atem18** [comment]
@rndusr There is no default ScrollBar, right ?

Because I checked on the official repo and there is none.

I have to use yours (https://github.com/rndusr/stig/blob/master/stig/tui/scroll.py) , right ?


Thanks a lot for the answers

**Comment by rndusr** [comment]
Yes, unfortunately, you have to copy the code.

It's not in urwid because of the minor bugs I mentioned earlier that I don't
know how to fix.

**Comment by Atem18** [comment]
@rndusr Ok thanks I will give it a try

**Comment by Atem18** [comment]
I tried and when using it :
`ScrollBar(urwid.Text(commands[self.caption]['command'](**parameters)))`

I get the following exception:
> ValueError: Not a box widget: <Text flow widget '\nOK, processing command...\n\n-- Status of application --\nOK -'>

**Comment by rndusr** [comment]
Sorry, my mistake. You need to wrap the Text in a Scrollable first:

    ScrollBar(Scrollable(urwid.Text(...)))

**Comment by Atem18** [comment]
@rndusr Thanks, I will test it.

**Comment by Atem18** [comment]
@rndusr It still does not work :/
My code:
`response = ScrollBar(Scrollable(urwid.Text(commands[self.caption]['command'](**parameters))))`
Stack trace:
`AttributeError: 'ScrollBar' object has no attribute 'rows'`

**Comment by rndusr** [comment]
Looks like ScrollBar is a box widget and you're wrapping it in a widget that
expects a flow widget.

http://urwid.org/manual/widgets.html#box-flow-and-fixed-widgets

**Comment by Atem18** [comment]
@rndusr Indeed, that was it, thanks a lot, it's awesome !

**Comment by gerberb** [comment]
Really love this functionality https://github.com/rndusr/stig/blob/master/stig/tui/scroll.py wish we could get it into urwid master

**Comment by netrix** [comment]
It looks like this thread went dead. Is anyone working on getting Scrollbar into master?

**Comment by epakai** [comment]
Just a note for others looking for this feature. It has since been added to [panwid](https://github.com/tonycpsu/panwid) which is packaged in pip, and Debian/Ubuntu.

**Comment by danschwarz** [comment]
Now that urwid is under active development again 🎉, is it time to resurrect this feature request? @rndusr 's scrollbar works well and should be added to the core library, especially if the "minor bugs" that @rndusr mentions above can be addressed. (I don't think I've experienced any bugs using this scrollbar in the [toot ](https://github.com/ihabunek/toot)client UI, but YMMV)  Tagging @penguinolog for visibility

**Comment by danschwarz** [comment]
Thanks! Did you have any crash bugs with 2.4.2 (or any post -2.1.2 release) that needed fixing? I ask because I'm getting a report of an intermittent crash in toot that uses an older version of scrollable.py , not sure it's at all related, but thought I might get lucky..

**Comment by markqvist** [comment]
Not *yet*. Nomadnet has been running stable with Urwid 2.1.2 and it's own version of Scrollable for a long time, but I just updated it to 2.4.2 today, so it's a bit uncertain at this point. Have been monkeying around with it, and it seems all good so far, but not making any guarantees yet ;)

Feel free to grab it from the nomadnet repo and try it out though.

**Comment by penguinolog** [comment]
@markqvist can you make a PR with `Scrollable` to the urwid?
Since re-license permission was received, it will require only some extra tests.

Premission link: https://github.com/markqvist/NomadNet/pull/46#issuecomment-1892712616

**Comment by penguinolog** [comment]
Release 2.5.0 include `Scrollable` / `ScrollBar` and support for `ScroolBar` in the `ListBox`
