### ISSUE TITLE
Inconsistent behavior of nested flow widgets in ListBox and Overlay

### ISSUE THREAD

**Issue by imrek** [urwid/urwid#227]
Suppose you create a `WidgetWrap` subclass to implement some custom widget. A `Text` and a `Button` widget nested first in `Filler`s, then a `Column` and finally a `LineBox`.

```
class SomeWidget(urwid.WidgetWrap):
	def __init__(self):
		txt = urwid.Filler(urwid.Text("Text"))
		btn = urwid.Filler(urwid.Button("Click"))
		display_widget = urwid.Columns([txt, btn])
		urwid.WidgetWrap.__init__(self, urwid.LineBox(display_widget))
```
You then put it into an Overlay just to see how it looks like.

```
top = urwid.Overlay(
	SomeWidget(), 
	urwid.SolidFill("/"),
	width=("relative", 50),
	height=("relative", 50),
	align="center",
	valign="middle"
	)
urwid.MainLoop(top).run()
```

When your WidgetWrap subclass is ready to be used, you decide to put it into a ListBox. 

```
widgets = [SomeWidget()] * 5
walker = urwid.SimpleListWalker(widgets)
top = urwid.ListBox(walker)
urwid.MainLoop(top).run()
```
And suddenly your custom widget fails because: `AttributeError: 'Filler' object has no attribute 'rows'` [with no line of your own code pointed out in the traceback, other than the line where you call `MainLoop().run()`, making it really hard to track this down]. Then you discover that you need to unwrap the `Text` and `Button` from the `Filler`s to get the code running, -- and realize that your custom `WidgetWrap` subclass isn't self-contained because you need to tweak its _nested inner_ widgets to get it work in different containers.

**Comment by wardi** [comment]
Yep, the errors could be much clearer. We even have this one in the FAQ https://github.com/urwid/urwid/wiki/FAQ#what-does-the-attributeerror-xxx-object-has-no-attribute-rows-error-mean

WidgetWrap doesn't constrain widgets it lets you implement a widget with other widgets, so naturally if the contained widget isn't a flow widget it's not going to work in a ListBox

**Comment by imrek** [comment]
> so naturally if the contained widget isn't a flow widget it's not going to work in a ListBox

But both LineBox and the Columns are box/flow widgets.

**Comment by wardi** [comment]
LineBox and Columns are box/flow depending on their contents (and options settings for Columns)

**Comment by rndusr** [comment]
Regarding the unclear error messages, how about adding a `_validate_size` method to the `Widget` class? It would take the `size` tuple and always return `(maxcol, maxrow)`, using `pack` or `rows` depending on what the `sizing` method
returns. If anything goes wrong, it would raise a `SizingError` with a helpful message.

Would you pull that?
