### ISSUE TITLE
Terminal Example Crashes in Python 3

### ISSUE THREAD

**Issue by AutoAwesome** [urwid/urwid#242]
Hi Guys!

I have a reproducable bug with the terminal example. 
There are a few commands which makes urwid crash when running it in python 3.
For example:

1.  Start the terminal example: 
> python terminal.py
2. In the terminal type:
> links google.com
3. urwid will crash:

> Traceback (most recent call last):
>   File "terminal.py", line 56, in <module>
>     main()
>   File "terminal.py", line 53, in main
>     loop.run()
>   File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 278, in run
>     self._run()
>   File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 376, in _run
>     self.event_loop.run()
>   File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 682, in run
>     self._loop()
>   File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 710, in _loop
>     self._entering_idle()
>   File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 671, in _entering_idle
>     callback()
>   File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 564, in entering_idle
>     self.draw_screen()
>   File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 579, in draw_screen
>     self.screen.draw_screen(self.screen_size, canvas)
>   File "/usr/lib64/python3.4/site-packages/urwid/raw_display.py", line 838, in draw_screen
>     l = l.decode('utf-8')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: unexpected end of data

The same crash can be archived with:
> man test

Then just hit page down until you reach the end of the manpage. urwid will also crash then.

python -V
> Python 3.4.5

But when I try it with Python 2.7 it works like a charm.
python2 -V
> Python 2.7.12   

Is there anything else I can do or test for you guys to help find the culprit?

Greetings.

**Comment by and3rson** [comment]
I believe this was fixed in `python-dual-support`. Just checked and it really failed with previous versions, but works with current master.
Thanks for reporting!

**Comment by AutoAwesome** [comment]
I can confirm that it works with the current master. 
Thanks!
