### ISSUE TITLE
set_text of urwid.Text does not refresh a text on screen until a mouse or keyboard event

### ISSUE THREAD

**Issue by Mad-ness** [urwid/urwid#250]
Hi,

I'm faced with issue when I need to set up a new value of the Text widget in a thread. The problem is that the set_text() method does not update the displayed text until I click or press any key on a console.

Is there a way to re-render the Text widget within a value before a mouse or keyboard event?

My application is getting data in threads and I need to refresh the screen dynamically. Here is a example code.

```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import urwid
import time
from threading import Thread

counter = 0

def key_handler(key):
    if key in ['q', 'Q']: raise urwid.ExitMainLoop()

def update_text(widget):
    global counter
    while True:
        counter += 1
        widget.set_text('New value ' + str(counter))
        time.sleep(1)

if __name__ == "__main__":
    txt = urwid.Text(u'Counter start')
    fill = urwid.Filler(txt, 'top')
    t =  Thread(target=update_text, args=(txt,))
    t.setDaemon(True)
    t.start()
    loop = urwid.MainLoop(fill, unhandled_input=key_handler)
    loop.run()
```

Thank you,
Dmitrii

**Comment by Mad-ness** [comment]
Found a solution by myself,

Need to call the loop.draw_screen() after the set_text() call. Actually I was expecting that the set_text method calls redraw the Text widget immediately and without redraw the entire screen.

**Comment by wardi** [comment]
in general that's not a safe thing to do. if one thread is updating widgets while the main thread is drawing the screen you're likely to have a crash (a widgets size might change between calculating the space and drawing it) or you might even have two threads drawing the screen at the same time, corrupting the display completely.

It's better to communicate from your worker thread back to the main thread with a pipe, check out the watch_pipe method and subproc example (it works with threads as well as separate processes)
