### ISSUE TITLE
pip package outdated

### ISSUE THREAD

**Issue by seonon** [urwid/urwid#251]
Seem like pip package has outdated.
I installed urwid: `pip install urwid`, and the version is 1.3.1. However, it does not has the *italic* support:
```
urwid.display_common.AttrSpecError: Unrecognised color specification 'italics' in foreground ('light magenta,italics')
```
I checked the code in `display_common.py` and found that there's no `italic` kind of thing.

**Comment by and3rson** [comment]
@seonon 2.0.0 is on PyPi now.
