### ISSUE TITLE
Maintaining

### ISSUE THREAD

**Issue by and3rson** [urwid/urwid#263]
Hi,

In regards to the announcement: I've recently been extensively using urwid, so I think I can dedicate some time to be one of the contributors who support this project.

Few words about me: 11 years with *nix, >6 years with Python, terminal freak.

**Comment by rndusr** [comment]
I would also be happy to contribute a few classes and other stuff and however
else I can. Unfortunately, I don't understand urwid well enough to maintain it.

**Comment by wardi** [comment]
Thank you @and3rson you should have write access now, use it carefully and let me know if you need anything else :-)

**Comment by and3rson** [comment]
@wardi Thanks, however I still don't have write access yet. Can you check it?

**Comment by wardi** [comment]
@and3rson I think there's a link you have to click in your email to accept being a collaborator.

**Comment by and3rson** [comment]
Totally forgot about that. Thanks!
