### ISSUE TITLE
Widgets not resizing automatically when using GLibEventLoop

### ISSUE THREAD

**Issue by federicotdn** [urwid/urwid#267]
When using the default main loop, the following example works correctly: the text remains on the center of the screen, even when the terminal is being resized:

```python
import urwid

txt = urwid.Text("Hello World", align='center')
fill = urwid.Filler(txt)
loop = urwid.MainLoop(fill)
loop.run()
```

However, when using `GLibEventLoop` and after resizing the terminal, the text stays in the same spot, until the user presses a key:

```python
import urwid

txt = urwid.Text("Hello World", align='center')
fill = urwid.Filler(txt)
loop = urwid.MainLoop(fill, event_loop=urwid.GLibEventLoop()) # Use GLib event loop
loop.run()
``` 

For context, I'm using:
- Python 3.6.3
- Ubuntu 17.10
- `urwid` version `1.3.1-2ubuntu2`
- `python3-gi` (GObject Introspection) version `3.24.1-2build1`
- Gnome Terminal 3.24.2

**Comment by federicotdn** [comment]
Related: https://github.com/urwid/urwid/issues/25

**Comment by federicotdn** [comment]
It looks like `raw_display.Screen.signal_init()` sets up two signal handlers, one for SIGWINCH and another one for SIGCONT.  The [GNOME documentation](https://developer.gnome.org/glib/stable/glib-UNIX-specific-utilities-and-integration.html#g-unix-signal-source-new) recommends using their own signal handling system instead of the standard UNIX one, when using the `GLib` event loop (the current handlers are not being called when using `GLib`).

I'll try moving the signal handlers setup code to `main_loop.py`, so that each `MainLoop` can setup the signal handlers properly.  The `GLib` signal handlers have different signatures, and must return either `GLib.SOURCE_CONTINUE` or `GLib.SOURCE_REMOVE` to indicate if the signal must be continued to be handled or not, respectively.

**Comment by federicotdn** [comment]
I've been working on top of the `python-dual-support` branch, should I wait until it's merged before I create a PR? @and3rson

**Comment by and3rson** [comment]
@federicotdn I think you can create the PR right away - the diff will automatically list only your new commits once we merge `python-dual-support`.
