### ISSUE TITLE
Python 2 doesn't have `.with_traceback`

### ISSUE THREAD

**Issue by atsampson** [urwid/urwid#275]
##### Description:
The code in `main_loop.py` to reraise exceptions doesn't work in Python 2.

##### Affected versions (if applicable)
Latest stable version (2.0.0) from `pypi`.

##### Steps to reproduce (if applicable)
Run the test suite with Python 2.

##### Expected/actual outcome
The test suite should pass. Instead, it fails with an `AttributeError`, as Python 2's exceptions don't have `with_traceback`; there are three exception handlers that use it.

There's some discussion of this in a different context in #92. One reasonably straightforward fix would be to copy `six.reraise` into `urwid.compat`.

**Comment by and3rson** [comment]
@atsampson thanks for the report! I'll take a look at it tomorrow.
