### ISSUE TITLE
Support for grabbing ctrl-c

### ISSUE THREAD

**Issue by rndusr** [urwid/urwid#277]
I think raw_display.Screen should have an option to call `tty.setraw()` instead of `tty.setcbreak()` so that pressing ctrl-c no longer raises KeyboardInterrupt and becomes a normal keypress event.

I'd be happy to make a PR.

**Comment by and3rson** [comment]
I agree, there are certain cases when this may be very useful. We can probably keep this disabled by default but provide a method to override it to handle ctrl-c manually.

**Comment by wardi** [comment]
@rndusr I think you want tty_signal_keys, e.g. https://github.com/urwid/urwid/blob/master/examples/input_test.py#L85

**Comment by rndusr** [comment]
Thanks, that works great.

This resolves the issue for me, so I'll close it.
