### ISSUE TITLE
Reverse colors

### ISSUE THREAD

**Issue by EnricoBilla** [urwid/urwid#282]
Hello,
I'm just searching for a way to reverse the default foreground and background color.
Here is an example of what I mean, but instead of the urwid.LIGHT_GRAY I'd like to use the console default color.

![screenshot_20180208_171441b](https://user-images.githubusercontent.com/25234601/35984610-1b596e2c-0cf5-11e8-9b58-ed408a3e82d8.png)

I really appreciate any help you can provide.
EnricoBilla

**Comment by wardi** [comment]
sure, it's called `'standout'`: http://urwid.org//manual/displayattributes.html?highlight=standout#bold-underline-standout

**Comment by EnricoBilla** [comment]
Thank you very much, I've been searching for it for a lot of time!
