### ISSUE TITLE
Unicode characters appear as 

### ISSUE THREAD

**Issue by Kamik423** [urwid/urwid#286]
##### Description:

I tried the [Horizontal Menu Example](http://urwid.org/tutorial/index.html#horizontal-menu), it works, but all unicode symbols appear as question marks. Putting unicodes symbols in menu names etc. results in the same. However printing them before the program works.
I tried the `\N{}`, `\u` and literal notation. All result in the same.

MacOS 10.13.3, iTerm 3.1.5, DejaVu Sans Mono

![screenshot](https://i.imgur.com/jLKVG1r.png)

##### Affected versions (if applicable)

- [ ] `master` branch (specify commit)
- [X] Latest stable version from `pypi`
- [ ] Other (specify source)

**Comment by tonycpsu** [comment]
@Kamik423 : I'm also on OS X.  I use the Menlo font, but I don't think this is a font issue.  Can you (and anyone else who's having this problem, e.g. @laixintao) tell me what the value of your `LC_CTYPE` variable is?  Mine is normally set to `en_US.utf8`.  If I set it to `en_US`, I get question marks like you guys.

**Comment by laixintao** [comment]
@tonycpsu Mine is :

```
➜  ~ echo $LC_CTYPE
UTF-8
```

I set to `en_US.utf8` it's still not working, but when I set to `en_US.UTF-8` it worked!

**Comment by tonycpsu** [comment]
Uh yeah, that was my mistake.  Glad it's working.

Given this, I'm not sure there's a bug here, @Kamik423 .  `LC_CTYPE` is what sets the encoding for your terminal.  If it isn't configured to display UTF-8 characters, they won't display properly.

**Comment by laixintao** [comment]
@Kamik423 I will check the Environment  `LC_CTYPE` and if can not display UTF-8 characters, I will choose something maybe ASCII as an alternative. FYI.

**Comment by ulidtko** [comment]
This is a common OSX issue. It sets locale environment to an incorrect value by default (just `UTF-8` is *not* a valid locale name), and the user has to correct it to a standard recognized value. I've met this kind of breakage before, and there's nothing libraries/apps can do.

We could document this though, giving a "canonical" workaround. Is it setting `LC_ALL=lang_code.UTF-8` via bash_profile? Or is it the Terminal.app checkbox about locale environment?

**Comment by Kamik423** [comment]
I just tried the example again. It is working on both my MacBook and my iMac. On both neither `LC_CYTPE` or `LC_ALL` yields any result. `LANG` is set to `en_US.UTF-8`.

My default shell is fish, but the same happens in bash too.

The `locale` command however yields this result:

```bash
$ ~> locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by tonycpsu** [comment]
OK sounds like everyone's got it figured out now.
