### ISSUE TITLE
Unable to run asyncio_socket_server example

### ISSUE THREAD

**Issue by xandfury** [urwid/urwid#290]
##### Description:
Sorry if this is a stupid question. I am unable to run **demo2** from `asyncio_socket_server.py` example on my system. 

*Traceback*
```
OK, good to go!  Try this in another terminal (or two):

    socat TCP:127.0.0.1:12345 STDIN,raw

Got a client!
Exception in callback UrwidProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle UrwidProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "./async_io.py", line 153, in connection_made
    self.urwid_loop.start()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 337, in start
    self.screen.start()
  File "/usr/local/lib/python3.5/dist-packages/urwid/display_common.py", line 751, in start
    self._start(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 219, in _start
    fd = self._term_input_file.fileno()
AttributeError: 'NoneType' object has no attribute 'fileno'
```

##### Version Info
- Latest stable version from `pypi` (version '2.0.1')
- Python 3.5.2

##### Steps to reproduce (if applicable)
Using the above versions, copy the contents of asyncio_socket_server.py on the system and run it with '2' option. Next, connect a client using telnet or `socat TCP:127.0.0.1:12345 STDIN,raw`

##### Expected/actual outcome
I should get the same TUI as I do when I run demo1 for every client that connects.

**Comment by xandfury** [comment]
Closing since I got no response. Thanks but I ended up using some other library.

**Comment by RyanKung** [comment]
Same issue.

@xandfury so what lib are you using now
