### ISSUE TITLE
Key press issue ('e' treated like 'esc')

### ISSUE THREAD

**Issue by johndeaton** [urwid/urwid#300]
Hi all-

I am having trouble with key press handling.  I'm handling all key presses via "unhandled_input" set in the MainLoop function.  Everything you see in the code below is working well except for the 'e' key.  It is being treated like the escape key.  Any ideas?  Are there further details I can provide to help troubleshooting?  I just downloaded the library via pip a few days ago, so it should be the latest version.  I'm running Linux.

Thanks,
John

```
currentHighlight = 0
# Define function for key presses
def optionSelection(key):
    global currentHighlight
    if key in ('q', 'Q'):
        with open('.TodoList.txt', 'wb') as f:
            pickle.dump(TaskList, f, pickle.HIGHEST_PROTOCOL)
        raise urwid.ExitMainLoop()
    if key in ('up'):
        if currentHighlight != 0:
            moveUp()
            changeMenu(True)
    if key in ('down'):
        if currentHighlight != 0:
            moveDown()
            changeMenu(True)
    for num in range(10):
        if key in (str(num)):
            numericSelect(num)
            changeMenu(True)
    if key in ('esc'):
        if currentHighlight != 0:
            currText = mainWidget[currentHighlight].base_widget.get_text()
            currTextonly = currText[0]
            taskTxtOnly = '   ' + currTextonly[3:]
            mainWidget[currentHighlight].base_widget.set_text(('nonHighlighted', taskTxtOnly))
            currentHighlight = 0
            changeMenu(False)
    if key in ('right'):
        displayMoreInfo()
    if key in ('left'):
        displayLessInfo()
    if key in ('e'):
        pass
```

```
loop = urwid.MainLoop(mainAttrMap, palette, unhandled_input=optionSelection)
loop.run()
```

**Comment by wardi** [comment]
`('esc')` is not a tuple in Python. I think you mean `if key in ('esc',):` or even better `if key == 'esc':`

**Comment by johndeaton** [comment]
Hi Wardi-

Thanks for the response.  That fixed it after I changed all the statements from "if key in..." to "if key == ..."  It is weird that the code was working fine before I added the last statement.  I'm not understanding that.  Let me know if you can think of why that might be the case.  

I see you contribute to this code.  Very cool.  I'm really liking it.  Good job to you and the rest of the guys!
