### ISSUE TITLE
GridFlow focus (again)

### ISSUE THREAD

**Issue by andrewcooke** [urwid/urwid#301]
##### Description:
The problem described in issue #61 (and fixed in [pull request 74](https://github.com/urwid/urwid/pull/74)) seems to have re(?)appeared:

##### Affected versions (if applicable)
- Version 2.01 (from pypi), Python 3.5.1

##### Steps to reproduce (if applicable)
<pre>
import urwid

a = urwid.Text(u"Text A")
b = urwid.Button(u"Button B")

grid = urwid.GridFlow([a,b], cell_width=36, h_sep=2, v_sep=1, align='left')
fill = urwid.Filler(grid, 'top')
loop = urwid.MainLoop(fill)
loop.run()
</pre>

##### Expected/actual outcome
Reverse a/b and the button is selectable.  Code as above, button is not selectable.

This example taken from #61, but I have a larger example in my own code (dates in a calendar, where the first day of the month is not Monday).

**Comment by tonycpsu** [comment]
@andrewcooke : I can't reproduce with urwid==2.0.1.  Button is selectable regardless of the ordering of `a` and `b` in the list.

**Comment by penguinolog** [comment]
Issue is fixed
