### ISSUE TITLE
How to force urwid to redraw the full frame ?

### ISSUE THREAD

**Issue by yanzixiang** [urwid/urwid#302]
Hi,there,I use Cascading Menu in the tutorial as an example,
and I want to use nmtui-edit to edit the system network settings,

```python3
menu_top = menu(u'YZXFDMaster', [
  sub_menu(u'配置 (Config)', [
    sub_menu(u'网络地址 (Network Address)',[
      menu_button(u'编辑 (nmtui-edit)', nmtui_edit_chosen),
      menu_button(u'连接 (nmtui-connect)', nmtui_connect_chosen),
    ] ),
  ]),
  sub_menu(u'控制 (Control)', [
    menu_button(u'重启服务 (Restart Master)', Restart_chosen),
    menu_button(u'重启系统 (Reboot System)', item_chosen),
  ]),
  sub_menu(u'状态 (Status)', [
    menu_button(u'Appearance', item_chosen),
    menu_button(u'Lock Screen', item_chosen),
  ]),
])
```

nmtui_edit_chosen to call nmtui-edit
```python3
def UpLevel(self):
    self.original_widget = self.original_widget[0]
    self.box_level -= 1

def nmtui_edit_chosen(button):
  subprocess.call("/usr/bin/nmtui-edit")
  top.UpLevel()
  frame._invalidate()
  frame.render((500,500))
```

at the end of the python file, just as the tutorial,
```python3
frame = urwid.Frame(urwid.AttrWrap(top, 'body'), header=header,footer=None,focus_part="body")
loop = urwid.MainLoop(frame, palette,screen=urwid.raw_display.Screen())
loop.run()
```
everything runs OK,
but after i close the nmtui-edit programe,
the header to the frame disappeared,

How to force urwid to redraw the full frame ?

**Comment by geier** [comment]
Instead of redrawing the whole screen, I would advise to stop the main loop first, run the external program and then restart the loop again:

```
loop.screen.stop()
subprocess.call("/usr/bin/nmtui-edit")
loop.screen.start()
```

**Comment by tonycpsu** [comment]
> Instead of redrawing the whole screen, I would advise to stop the main loop first, run the external program and then restart the loop again:

I am having a similar issue as the original reporter, and for me, doing a screen stop / start does indeed cause the screen to be redrawn, but program input is no longer processed, and I have to Ctrl-C out of the app. 

Urwid 2.0.1.  Test code here:

```
import logging
import os
import subprocess

import urwid
import urwid.raw_display
from urwid_utils.palette import *

loop = None

def global_input(key):
    global loop
    if key in ('q', 'Q'):
        raise urwid.ExitMainLoop()
    elif key == "!":
        loop.screen.stop()
        proc = subprocess.call(
            "top",
            shell=True
        )
        loop.screen.start()
        loop.draw_screen()


def main():

    global loop

    palette = [

        ('normal', 'white', 'black', '', "white", "black"),
    ]

    screen = urwid.raw_display.Screen()
    screen.set_terminal_properties(256)
    loop = urwid.MainLoop(
        urwid.Filler(urwid.Text("foo")),
        palette,
        screen=screen,
        unhandled_input=global_input,
    )

    loop.run()

if __name__ == "__main__":
    main()
```

Commenting out the `loop.screen.stop()` and `loop.screen.start()` calls doesn't interfere with input, but forces the user to manually clear the screen after `top` exits with "Ctrl-L".

**Comment by Phalangers** [comment]
`loop.screen.clear()` redraws the whole screen.
Might be what you're looking for.
