### ISSUE TITLE
Smoothing progress bars doesn't work

### ISSUE THREAD

**Issue by rr-** [urwid/urwid#317]
##### Description:
Progress bars seem to be unable to use the smoothing feature.
Python 3.7.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
Create a progress bar, set its progress to miniscule value

##### Expected/actual outcome
It should use the `eighths` variable (`▏▎▍▌▋▊▉`)
It uses only full blocks instead

The reason seem to be in this check:
https://github.com/urwid/urwid/blob/master/urwid/graphics.py#L945

Here, the value of `c._text[0][ccol]` on my machine is `32` (an integer) rather than `" "` (a string).

**Comment by ntamas** [comment]
I can confirm that simply replacing `c._text[0][ccol] == " "` with `ord2(c._text[0][ccol]) == 32` solves the issue and does not break compatibility with Python 2.x. (`ord2` has to be imported from `urwid.compat`).

Note that this is not purely a cosmetic issue; on Python 3.x, if the percentage of the progress bar is so small that the first character would be a block character from `eighths` (a percentage of 1% with a sufficiently narrow progress bar would do), this bug essentially collapses the progress bar to zero width when it is used in a `Columns` widget as parent as we end up in the wrong branch in the rendering method and we render nothing.

**Comment by ulidtko** [comment]
Fix merged, will appear in the next release.
