### ISSUE TITLE
Use terminfo to get terminal capabilities and escape sequences

### ISSUE THREAD

**Issue by inducer** [urwid/urwid#33]
[renamed issue as problem below has been worked around for now] -wardi

When I run Urwid's `examples/browse.py` within [tmux](http://tmux.sourceforge.net/) 1.8, the screen looks like this:

![tmux-broken](https://f.cloud.github.com/assets/352067/671760/f9fe9e92-d864-11e2-895d-79cff3e124b1.png)

As you can see, the trailing ends of each line have the underlying (yellow-ish) terminal color showing through.

I use urwid 1.1.1. As you can see in the config below, my $TERM is set to `screen-256color`. Both gnome-terminal and konsole as outer terminals show this behavior.

The same program within GNU screen is fine:

![screen-ok](https://f.cloud.github.com/assets/352067/671759/f3fd0d6c-d864-11e2-92f4-426addcfbd95.png)

Here's my .tmux.conf:

```
set -g prefix C-a
setw -g mode-keys vi
setw -g aggressive-resize on
set -g status-keys vi
set -g default-terminal "screen-256color"
set -g update-environment "DISPLAY WINDOWID SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION XAUTHORITY XDG_SESSION_COOKIE DBUS_SESSION_BUS_ADDRESS SESSION_MANAGER"

set -g alternate-screen on

unbind C-b
bind a send-prefix
unbind h
unbind l
bind h select-window -t :-1
bind l select-window -t :+1
bind C-a last-window

set -g status-bg black
set -g status-fg white
set -g history-limit 10000
setw -g window-status-bg black
setw -g window-status-fg white
setw -g window-status-current-bg colour240
setw -g window-status-current-fg white
setw -g window-status-current-attr bold
```

I'm not exactly sure whose fault this is--could be urwid, tmux, or something else entirely. Any help would be much appreciated.

**Comment by and3rson** [comment]
I'm closing this as it seems to be fixed.
