### ISSUE TITLE
Gap between LineBoxes in adjacent columns

### ISSUE THREAD

**Issue by rgov** [urwid/urwid#337]
##### Description:
I have a `Columns` container with two `LineBox`es. They are set so that they should share the dividing vertical line, but there is a gap.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/108767/55131588-92b42580-50f5-11e9-81ba-fcad18aeb6b5.png">

##### Affected versions (if applicable)
Latest stable version from `pypi` (2.0.1)

##### Steps to reproduce (if applicable)
```
urwid.Columns([
      urwid.LineBox(
        urwid.Text('lol'),
        rline='', trcorner='', brcorner=''
      ),
      urwid.LineBox(
        urwid.Text('wtf'),
      ),
    ])
```

Setting `dividechars` to -1 resolves it but I don't think that should be necessary.

**Comment by penguinolog** [comment]
You need to set corners explicit for joined lines since empty "rline" does not mean "nonexistent".
```python
>>> print(
    urwid.Columns([
        urwid.LineBox(urwid.Text('lol'), rline='', trcorner='─', brcorner='─'),
        urwid.LineBox(urwid.Text('wtf'),tlcorner="┬", blcorner="┴"),
    ]).render(()))
┌────┬───┐
│lol │wtf│
└────┴───┘
```
