### ISSUE TITLE
Adding new Urwid maintainer(s)

### ISSUE THREAD

**Issue by wardi** [urwid/urwid#338]
@tonycpsu has offered to step up to review our backlog of pull requests and issues. I'd like to make sure urwid continues to be well maintained so I'm planning to add Tony as a maintainer. Is there anyone else that would be willing to help?

**Comment by tonycpsu** [comment]
Ping:
@hootnot 
@ulidtko 
@federicotdn 
@geier

**Comment by geier** [comment]
While I'd love to help out, my free time is currently in such short supply, that I can't take proper care of [khal](https://github.com/pimutils/khal). Sorry.

**Comment by ulidtko** [comment]
Hey! I'd like to take a part in this.

I'm currently in a team where we employ Urwid in one of important components. Thus, there's a number of items in my TODO related to Urwid (and also some capacity to working on it). #304 is already done, hope to do more!

**Comment by hootnot** [comment]
Sorry, but  I'm in the same category as @geier

**Comment by wardi** [comment]
sent invites! Thank you and welcome @tonycpsu and @ulidtko
