### ISSUE TITLE
Use standard terminal coloring with Text

### ISSUE THREAD

**Issue by italomaia-bk** [urwid/urwid#361]
##### Description:
I wish to use pieces of text with styling inside Text without set the styling for the whole Text widget. Could support for this be added or is this by design?

##### Affected versions (if applicable)
- [x ] `master` branch (specify commit)

##### Steps to reproduce (if applicable)
Try to use colr library with a Text widget. You will get plain text output without styling. 

##### Expected/actual outcome
Styled output.

**Comment by ulidtko** [comment]
Hi! Yes, it is possible, check this out: http://urwid.org/manual/displayattributes.html

Also see **`examples/calc.py`**, here's in-text styling:

![Screenshot from 2019-09-18 23-24-44](https://user-images.githubusercontent.com/365338/65183590-740f6580-da6c-11e9-9d93-ba6cfb55c3c5.png)

rendered from this code:

![Screenshot from 2019-09-18 23-25-53](https://user-images.githubusercontent.com/365338/65183287-d74cc800-da6b-11e9-8a17-4262ae94e382.png)

Thanks for an easy question! :)
Feel free to reopen.
