### ISSUE TITLE
Constructing a ListBox with just a list of items uses a PollingListWalker

### ISSUE THREAD

**Issue by inducer** [urwid/urwid#37]
and `PollingListWalker` is apparently deprecated. If using `ListBox` without an explicit `ListWalker` is supposed to be deprecated, then the error message should say so, instead of only mentioning `PollingListWalker`, which doesn't explicitly occur in user code that does this. If this use is not deprecated, then perhaps this should be switched to another `ListWalker`.

[Relevant code](/wardi/urwid/blob/master/urwid/listbox.py#L284)

**Comment by and3rson** [comment]
Seems like SimpleListWalker is now the fefault. I'm closing this as resolved.
