### ISSUE TITLE
Broken render on cygwin

### ISSUE THREAD

**Issue by buxx** [urwid/urwid#374]
##### Description:

My program works well under linux with special utf-8 chars. And work with Windows+Cygwin to but not when some utf-8 characters are used.

Example under linux with utf-8 special character (by special i mean character used in country when write right-to-left for example):

![Capture du 2019-08-12 14-54-15](https://user-images.githubusercontent.com/1104637/68997691-83aefd00-08a9-11ea-9cfc-ec0460f748fc.png)

With mintty in cygwin, this render is broken:

![VirtualBox_WinDev1907Eval_16_11_2019_19_40_31](https://user-images.githubusercontent.com/1104637/68997696-93c6dc80-08a9-11ea-8d10-224aed49ecb1.png)

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [X] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)

This is a long install but do the job (windows script): download all file in https://github.com/buxx/rolling/tree/master/windows and run install.bat

##### Expected/actual outcome

Same display as in linux

**Comment by penguinolog** [comment]
Please check with the last package version. It should explicit use `utf-8` mode under Windows

**Comment by buxx** [comment]
Too much old sorry, I will not be able to test that :D

**Comment by penguinolog** [comment]
Validated: cygwin support is fixed (BTW cygwin looks a bit deprecated with its strange python support).
