### ISSUE TITLE
ValueError: too many values to unpack (expected 1) when setting Frame body as a column

### ISSUE THREAD

**Issue by shadedKE** [urwid/urwid#376]
So as I was learning my way around urwid , I wanted to create a column widget using this code
```
import urwid
col =urwid.Columns([urwid.Text('heey'),urwid.Text("There")])
bdy = urwid.Frame(body=col)
urwid.MainLoop(bdy).run()
```

But I get an error each time I run it saying 
```
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 1000, in render
    (maxcol,) = size
  ValueError: too many values to unpack (expected 1)
```
Is there a reason for this?

**Comment by tonycpsu** [comment]
Yup, [see here](https://github.com/urwid/urwid/wiki/FAQ):

> **What does the "(maxcol,) = size ... ValueError: too many values to unpack" error mean?**

> One of your flow widgets is being treated like a box widget by another widget or by the MainLoop class. For example, the topmost widget used by the MainLoop class and widgets used the body of a Frame widget must be box widgets.

> If you want to use a flow widget where a box widget is expected you need to first wrap it with a widget like Filler that will take care of filling the empty space above or below what the flow widget displays.

Fixed example:
```python
import urwid
col =urwid.Columns([urwid.Text('heey'),urwid.Text("There")])
bdy = urwid.Frame(body=urwid.Filler(col))
urwid.MainLoop(bdy).run()

```

**Comment by shadedKE** [comment]
Thanks very much

**Comment by yaniv-aknin** [comment]
Curious why it appears adding `height=1` to the Filler seems to break this?

Wrote a [full question](https://stackoverflow.com/questions/66060115/urwid-raising-maxcol-size-too-many-values-to-unpacl) about it in StackOverflow.
