### ISSUE TITLE
Progressbar not updating in a for loop

### ISSUE THREAD

**Issue by shadedKE** [urwid/urwid#380]
##### Description: Progress bar not updating inside a for loop

I created a progress bar but it's not updating inside a for loop update happens when the for loop is closed 
My code looks like this 
```
  pbar =urwid.Progressbar('a','b')
  for i in range(1,100)

    pbar.setcompletion(i)

    #To see the pbar increment 
    time.sleep(5)
   pbar.setcompletion(100)
```
Am only getting the last completion

How can i get it to update in the for loop?

**Comment by tonycpsu** [comment]
Please include a complete example including imports, mainloop., etc.

**Comment by shadedKE** [comment]
The real code is really long (700 lines)
But i still get the same problem here
```
import time
Import urwid

progbar=urwid.Progressbar('a','b')

def pbar(*args):
    global progbar
    for i in range(1,100):
        progbar.set_completion(i)
        progbar.render((10,))
        time.sleep(1)
btn=urwid.Button('Go',on press=pbar)
frame=urwid.Frame(urwid.Filler(urwid.Pile([progbar,btn])
if __name__=='__main__':
    loop=urwid.Mainloop(frame)
    loop.run()
```

**Comment by alethiophile** [comment]
You aren't redrawing the app between renders. Try calling loop.draw_screen inside the for loop (need to pass a reference to loop).
