### ISSUE TITLE
Unicode rendering problems in Terminal 

### ISSUE THREAD

**Issue by d0c-s4vage** [urwid/urwid#383]
##### Description:
As described in #359, Terminals do not render unicode output correctly. E.g.

```bash
$> echo -en "☺" | xxd
00000000: e298 ba                                  ...
$> echo -e "test \xe2\x98\xba  test"
test ☺  test
```

And then in a Terminal instance:

![image](https://user-images.githubusercontent.com/5090146/70858338-2fea0080-1eb5-11ea-8d4f-b8d209cef438.png)

##### Affected versions (if applicable)
- [x] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
Have a terminal print unicode glyphs to its stdout. E.g.

```
echo -e "test \xe2\x98\xba  test"
```

##### Expected/actual outcome

The `echo` above should result in this being printed:

```
test ☺  test
```

**Comment by d0c-s4vage** [comment]
This is a user-error. To get an embedded terminal to display encodings correctly, the global urwid encoding needs to be set:

```python
urwid.set_encoding('utf8')
```

**Comment by ulidtko** [comment]
Well, I'd hold that UTF-8 should be enabled by default, and explicit `set_encoding` calls would only be necessary for non-utf8 locales. It's year 2020 (very soon), after all.

The doc PR is very enticing to merge already... I'll merge with a comment.
