### ISSUE TITLE
Urwid with TrioEventLoop uses select() in addition to epoll

### ISSUE THREAD

**Issue by joernheissler** [urwid/urwid#390]
##### Description:

When using urwid with TrioEventLoop, I expect that only epoll is used, and not select. But both are used.

##### Affected versions (if applicable)
- [X] `master` branch (specify commit)

  * urwid f27d0227f9788c53965a34320a58c718c2f2adae
  * trio 79c8f6353251086843defacab47d984d5a069bb0

- [ ] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)

Run a simple example program, e.g. http://urwid.org/tutorial/index.html#display-attributes with `event_loop=urwid=TrioEventLoop()` inside strace. Then press some keys on the keyboard.

##### Expected/actual outcome

Actual:

I see a loop which consists of those lines:
```
epoll_ctl(5, EPOLL_CTL_MOD, 0, {EPOLLIN|EPOLLONESHOT, {u32=0, u64=0}}) = 0
epoll_wait(5, [{EPOLLIN, {u32=0, u64=0}}], 3, 86400000) = 1
select(1, [0], [], [0], {tv_sec=0, tv_usec=0}) = 1 (in [0], left {tv_sec=0, tv_usec=0})
read(0, "H", 1)                         = 1
select(1, [0], [], [0], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
read(3, 0x7f656a6cdd70, 1)              = -1 EAGAIN (Resource temporarily unavailable)
```

Expected:
I expect that `select()` is not used. `epoll_wait` already indicates that fd 0 is readable.

**Comment by penguinolog** [comment]
Urwid not calling `select` or `epoll` by itself in case of `TrioEventLoop` usage. In case of issue still actual, it should be handled in `trio` package.
