### ISSUE TITLE
urwid-2.1.0 byte-compiling with py2.7 failed due to _async_kw_event_loop.py (py3 only)

### ISSUE THREAD

**Issue by clemat** [urwid/urwid#393]
Following quick chat with @ulidtko on your gitter community, I am opening this Issue for the record. Even thought there's a valid workaround it would be nice to have it fixed upstream.

##### Description:
File "/usr/local/lib/python2.7/site-packages/urwid/_async_kw_event_loop.py", line 164
    async def _alarm_task(self, scope, seconds, callback):
            ^
SyntaxError: invalid syntax

py2 doesn't support async stuff. This is impacting distribution packages (error when building bytecode). 

removing _async_kw_event_loop.py post-extract for py2 is a valid workaround.
Couldn't this be "excluded" via setuptools? Or other ways. So it doesn't impact all distribution packages and ports.

##### Affected versions 
- 2.1.0

**Comment by penguinolog** [comment]
Python 2.7 support ended. New release drop it
