### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by and-semakin** [urwid/urwid#394]
##### Description:
Python 2 reached its EOL December 31, 2019. I understand that ~30% of urwid users still on Python 2 at the moment (according to [PyPI stats](https://pypistats.org/packages/urwid)).

Advantages of dropping Python 2:
* decrease burden of development and maintenance;
* no more `six`, no more `str`/`bytes` errors;
* new language features supported (for example, `asyncio` module, type hints).

What's urwid's deprecation policy about old Python versions?

**Comment by tonycpsu** [comment]
It seems to me whatever norms / policies around deprecation may have existed previously for the project wouldn't necessarily apply to such an important, ecosystem-wide change as the EOL of Python 2.  It has taken a lot of blood, sweat, and tears to get folks to overcome their resistance to upgrading, and many would say that it's long overdue.

This makes me think that any attempts to continue supporting the EOLed version would be extremely counterproductive.  If someone wants to continue using Python 2.x despite the EOL, they can use older urwid versions.  If that prevents them from using some new functionality, it's not like they weren't warned for the past nine years (PEP 404 was written in 2011).  

I would support ripping the band-aid off now and dropping Python 2.x support ASAP.

See also #393.

**Comment by ulidtko** [comment]
Py3 migration is indeed a well-beaten path, and a fertile topic for stories.

It's well about the time for Urwid to do it, too.

I've played several roles in this drama, been fighting on both sides; let me suggest a polite way to do it.

 1. Drop Py2 support from the **mainline branch**, `master` in our case — where all development happens, where PRs are getting merged into, where 2.1.x and later releases are cut from.
 2. **Keep** Py2 compat in a *life support* branch — 2.0.1 and later minor releases (2.0.2, 2.0.3 etc). No new features in this branch, not even "doc typo" PRs, no any changes if at all possible — the branch is reserved for critical fixes only.

For a good example, see [pytest](https://github.com/pytest-dev/pytest/branches) — their `4.6.x` branch keeps Py2 compat and minimum activity, while `5.3.x` and `master` have dropped py2 and moved along.

**Comment by neiljp** [comment]
Has there been any progress on this?

**Comment by penguinolog** [comment]
In master: project is python 3.7+ - only
