### ISSUE TITLE
Point release for fixes?

### ISSUE THREAD

**Issue by alethiophile** [urwid/urwid#403]
##### Description:
I'm currently writing a program that depends on a fix that hasn't been released yet (#381, specifically). I'd like to release it, but depending on the head branch here is a pain.

**Comment by ulidtko** [comment]
Ah yes, sure, we should do it.

Currently, the release process isn't documented AFAICS. I could've guessed my way through it, but better let @tonycpsu do it (and document along the way).

Feel free to ping if we stagnate with this again.

**Comment by mhils** [comment]
Hey folks,

I hate to leave these sorts of comments, but since @ulidtko explicitly invited them - we'd be very interested in having a patch release as well. Thanks y'all for the effort. :)

**Comment by tonycpsu** [comment]
Nah, you're not wrong to nudge us on this one.  I said I'd get a 2.1.1 release out but then got sidetracked by starting a new day job.  I'll try to get it out ASAP.

**Comment by tonycpsu** [comment]
Finally got around to pushing the release out, and added [a script](https://github.com/urwid/urwid/blob/master/bin/release.sh) to automate the release process a bit.  Hopefully this will enable us to get patch releases out on a more frequent basis.

**Comment by mhils** [comment]
Thanks so much @tonycpsu! 🍰
