### ISSUE TITLE
Pudb shows source unicode as '?' because urwid thinks source is ASCII

### ISSUE THREAD

**Issue by anttin2020** [urwid/urwid#410]
##### Description:
Hi!
I have problem with pudb and the author said it is problem in urwid (based on pudb crash log, see below). He provided fixed version so no crash anymore but still pudb shows the source unicode as '?'.

I installed pudb with pip and it installed urwid 2.1.0.

There was another pudb-related issue here but it is not the same (could be related, I don't know) so I posted this as new issue :)

##### Steps to reproduce (if applicable)
make test.py:
```
#!/opt/alt/python37/bin/python3
# -*- coding: utf8 -*-

s="testing unicode äöäöäö"
print(s)
```
1. install pudb: python3 -m pip install pudb
run it: python3 -m pudb.run test.py
->crash -> [pudblog.txt](https://github.com/urwid/urwid/files/4747803/pudblog.txt)
2. uninstall pudb: python3 -m uninstall pudb
3. install pudb: python3 -m pip install git+https://github.com/inducer/pudb.git@master
run it: python3 -m pudb.run test.py
no crash and it works but unicode is shown as '?'

##### Expected/actual outcome
Unicode characters should show up correctly.

Can you please help with this? :)

**Comment by anttin2020** [comment]
Thank you for the 'cinema', it definitely shows it works :)

And for me it worked with VSCode terminal but not with Bitvise SSH Client terminal which is xterm.
Strange thing was that if I ran the test.py directly, it showed the characters correctly so in that point of view the terminal could show unicode correctly.

However, based on that I checked the locale settings in the plain terminal and it was all 'POSIX' :o
When I added the 
```
LANG="en_US.utf8"
export LANG
```
to the .bash_profile, it started to work perfectly :)
So probably VSCode terminal has its own locale settings and that's why pudb worked there.
Strange thing is still, why it worked directly with python3 test.py but anyway, the problem is now gone!

The only thing that is still strange but probably has nothing to do with pubd nor urwid but if you still have any ideas, is the a bit 'ugly' colors on my terminal compared to VSCode terminal (that looks the same as yours). I use xterm-256colors (plain xterm does not give the colored code), see the capture below. And Bitvise SSH Client terminal claims to show full colors: [https://bitvise.com/ssh-client#term](https://bitvise.com/ssh-client#term).
So can this be another linux setting problem? I am not a linux guru, to say the least so if you have any ideas, even though this is off-topic, please share :)

Anyway, thank you very much for your help and have a nice day!

![bitvise-ssh-client-xterm256colors](https://user-images.githubusercontent.com/65116899/84346889-bdcf4b80-abb9-11ea-8604-e32cff940613.png)

**Comment by anttin2020** [comment]
Fish shell looks nice and I might try it but I don't have sudo rights (the remote system I use is a webhotel based on cPanel system (virtual servers shared with about 400 customer areas each):
`Linux version 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64 (mockbuild@buildfarm03.cloudlinux.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Wed May 29 04:37:40 EDT 2019`
I couldn't figure out if and how I can use Fish, can you confirm that? There is no option for RedHat in the downloads and I'm afraid it needs sudo rights.
And of course it does not solve the color problem but it seems nicer than bash that I am using now.

I totally understand that this is even more off-topic and I don't expect you to answer to this or the color problem but it just seems you are familiar with linux so it might be easy for you :)

**Comment by ulidtko** [comment]
Terminal color support is hairy business, I don't really grok it currently.

Check this thread: https://gist.github.com/XVilka/8346728
It has a couple scripts to test and diagnose terminal color issues. It also has extended discussion — but no mentions of BitVise, you might want to fix that :wink: 

Since you figured out the original Unicode issue — I'm going to close this one, there's no changes for urwid code to be made. If you do find that color issues are urwid-specific — feel free to open another one :)

Thanks for you kind words, much appreciated!
