### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by vega0** [urwid/urwid#417]
##### Description:
Trying/learning library to create Frame with nested Columns as frame body, but getting strange error.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [+] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
Just put Columns widget into Frame body.

##### Expected/actual outcome
Separated columns in frame body
![image](https://user-images.githubusercontent.com/6493857/86499238-c8cd6400-bd92-11ea-92a5-5b38ff50e5be.png)

Code to test
```python
import urwid, sys

palette = [
	('banner', '', '', '', '#ffa', '#60d'),
	('streak', '', '', '', 'g50', '#60a'),
	('inside', '', '', '', 'g38', '#808'),
	('outside', '', '', '', 'g27', '#a06'),
	('bg', '', '', '', 'g7', '#d06'),
	('main_bg', '', '', '', 'g7', '#00f'),
	('edit', '', '', '', '#0ff', '#fff'),
]

class LoginWidget(urwid.Pile):
	
	def __init__(self, *args, **kwargs):
		
		self.t_login = urwid.Edit('login:', '', )
		self.t_passw = urwid.Edit(' pass:', '', mask='*')
		
		super().__init__([
			urwid.Text(u"Login Required.", align = 'center'),
			urwid.Divider(), self.t_login, self.t_passw,
			urwid.Button("OK", lambda *args: self.action_ok())
		], *args, **kwargs)
		
	def action_ok(self):
		pass

class VkContainer(urwid.Columns):
	
	def __init__(self, widgets, *args, **kwargs):
		super().__init__(widgets, *args, **kwargs)
		
class VkAppFrame(urwid.Frame):
	
	def __init__(self, *args, **kwargs):
		
		self.container = VkContainer([
			urwid.Text(("banner", u"Login Required."), align = 'center'),
			self.create_login_box(*args, **kwargs)
		])
		
		super().__init__(
			body = self.container, #body widget
			header = urwid.Text(u"HEADER.", align = 'center'),
			footer = urwid.Text(u"FOOTER.", align = 'center'),
			focus_part='body',
			*args, **kwargs)

	def create_login_box(self, *args, **kwargs):
		""" Creates new login box. """
		self.login_box = LoginWidget(*args, **kwargs)
		
		return self.login_box

class VkApp(object):
	
	Instance = None
	
	def __init__(self):
		VkApp.Instance = self
		placeholder = urwid.SolidFill()
		loop = urwid.MainLoop(placeholder, palette)
		self.loop = loop
		loop.screen.set_terminal_properties(colors=256)
		loop.widget = urwid.AttrMap(placeholder, '')
		loop.widget.original_widget = VkAppFrame()

	def run(self):
		
		self.loop.run()
		
	def widget_on_top(self, widget):
		self.loop.widget = widget

if __name__ == "__main__":
	VkApp().run()
```

**Comment by tonycpsu** [comment]
> [What does the "(maxcol,) = size ... ValueError: too many values to unpack" error mean?](https://github.com/urwid/urwid/wiki/FAQ)
> One of your flow widgets is being treated like a box widget by another widget or by the MainLoop class. For example, the topmost widget used by the MainLoop class and widgets used the body of a Frame widget must be box widgets.

> If you want to use a flow widget where a box widget is expected you need to first wrap it with a widget like Filler that will take care of filling the empty space above or below what the flow widget displays.

To fix, change line 46 to:

```python
    body = urwid.Filler(self.container),
```
