### ISSUE TITLE
Test Case Failure on OpenBSD: test_wrap_backspace_tab

### ISSUE THREAD

**Issue by wardi** [urwid/urwid#43]
trac ticket https://excess.org/urwid/ticket/98

**Comment by Apteryks** [comment]
The ticket link is dead.

**Comment by tonycpsu** [comment]
This link:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=655647

Suggests whatever this bug was can no longer be reproduced on OpenBSD.
