### ISSUE TITLE
str_util/old_str_util.get_width is returning incorrect width (2) for block U+1fb00 - U+1fbff

### ISSUE THREAD

**Issue by rbanffy** [urwid/urwid#433]
##### Description:
For the characters in the U+1FB00-FF block (at least - see https://en.wikipedia.org/wiki/Symbols_for_Legacy_Computing), the width being returned is incorrect. It seems the data in the file needs to be regenerated from the up-to-date document at https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt

##### Affected versions (if applicable)
- [X] `master` branch (specify commit)
- [X] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
I'm adding a new font that uses these symbols to offer improved rendering over the 2x2 mosaics from previous versions of Unicode. The (initial, digits-only) font can be found at https://github.com/rbanffy/urwid/blob/master/urwid/font.py#L179-L187

Interim fixes to get_width are on https://github.com/rbanffy/urwid/blob/master/urwid/old_str_util.py#L75 and https://github.com/rbanffy/urwid/blob/master/source/str_util.c#L80 (but they were not generated from the UCD mentioned in the bug description).

##### Expected/actual outcome
The font renders correctly (I used the bigtext.py program to run my tests)

**Comment by tonycpsu** [comment]
Appears to be a duplicate of #225 .

@rbanffy , can you try to install the branch pointed to in the last comment of that issue and see if things look better for you?

**Comment by rbanffy** [comment]
Yes, it's a duplicate. Sorry :-(
