### ISSUE TITLE
No Module Named urwid

### ISSUE THREAD

**Issue by Certseeds** [urwid/urwid#435]
##### Description:
hey, my environment is Ubuntu 18.04
i had run
sudo pip3 install urwid
sudo pip3 install urwidtrees
sudo apt install python3-urwid
sudo apt install python3-urwidtrees
but when I start a python console and `import urwid`.
there still output 
ModuleNotFoundError: No module named 'urwid'
what should I do to import urwid successful in python console?
PS: I had tree to use a file that only have a line which is `import urwid` and "python3 ./test.py" to run it, but it still can not import.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [x ] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
just pip,apt and use python console

##### Expected/actual outcome
[...]

**Comment by tonycpsu** [comment]
Please provide the output of:

`bash -c 'pip3 show urwid'`

and

`python3 -c 'import sys; print(sys.path)'`

**Comment by Certseeds** [comment]
I find that i use a special Software source.
when I use `sudo pip3 install urwid`, it can download but can not use in python console.
when  I use `pip3 instlal urwid`, it output `AttributeError: 'NoneType' object has no attribute 'lower'`.Although it can not run, but I run the command `sudo` successful so I ingore that.
After all, I use `pip3 install urwid -i https://pypi.tuna.tsinghua.edu.cn/simple`, which solve this problem.
