### ISSUE TITLE
urwid.ListBox

### ISSUE THREAD

**Issue by Abhirup-99** [urwid/urwid#445]
Add a len property in ListBox to return the length of the items that are being stacked.

**Comment by penguinolog** [comment]
Problem with `ListBox`, that it's not required to be a `list` based: It uses `ListWalker` interface and technically can use wrapped generator without real length.
`__len__` can be added to fixed-size container, like `Pile`, `Columns`, `Grid` and `Overlay` (the last one is a special case with fixed length == 2)
