### ISSUE TITLE
How do I get a nested Text widget to render?

### ISSUE THREAD

**Issue by marthinwurer** [urwid/urwid#455]
##### Description:
My goal is to wrap Urwid's text widget to create my own custom widget. To do this, I need to wrap the text widget in a Filler widget so I can render it the correct size. Unfortunately, when I do that it doesn't render.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
Run the following source code:
```python3
import logging
import urwid

logging.basicConfig(filename='example.log', encoding='utf-8', level=logging.DEBUG)
logger = logging.getLogger(__name__)


class TestWidget(urwid.WidgetWrap):
    def __init__(self):
        self.text_widget = urwid.Text("test")
        super().__init__(urwid.Filler(self.text_widget, valign='top', height='flow'))
        self._selectable = True

    def selectable(self):
        return self._selectable

    def keypress(self, size, key):
        if key in ('w', 's', 'a', 'd'):
            logger.info(key)
            self.text_widget.set_text(key)
        else:
            return key

def show_or_exit(key):
    if key in ('q', 'Q'):
        raise urwid.ExitMainLoop()

if __name__ == '__main__':
    logger.info("Starting")
    wid = TestWidget()
    loop = urwid.MainLoop(wid, unhandled_input=show_or_exit, handle_mouse=True)
    loop.run()
```

##### Expected/actual outcome
With this example code, I'm expecting to see "test" on my screen, then the key that I press if they're one of "wasd". Instead, I see nothing. Logging is telling me that I'm hitting my code in keypress, and previous debugging showed that I was hitting the `render()` function of the text widget and returning the correct value.

**Comment by tonycpsu** [comment]
Presence of the `encoding` argument to your `logging` setup suggests you're using Python 3.9, which isn't yet supported.  There's no reason why I would expect things not to work, of course, but if your issue is on an unsupported version of Python, it's best to note that in the report.

More importantly, when I do install 3.9 and run with it, your test code is working exactly as you describe.  Text widget, keypresses change the text.  So I'm really not sure what's going on here.

**Comment by marthinwurer** [comment]
Python, urwid, and OS details:

```
$ python --version
Python 3.9.0

$ pip list
Package    Version
---------- -------
pip        20.3.3
setuptools 49.2.1
urwid      2.1.2

$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Comment by marthinwurer** [comment]
I was able to get it to work on another computer. I also was able to get it to work with a new virtualenv, but not the old one. It looks like something got screwed up with the old one somehow. I have reinstalled urwid and now it works.
