### ISSUE TITLE
Groups handling

### ISSUE THREAD

**Issue by Cela-02** [urwid/urwid#470]
Hi guys,
I have been messing around with qtile on my arch for several weeks and everithing is going great a part from 2 aspects:

1. when I launch an app which remains open in background after I have closed it (e.g. discord) it will be always open in that group. I would like instead to open it in the group where I am when I launch it in that moment, which could be a different one from the first. Is it possible?

2. when I try to share my screen using for instance discord or google meet, I can only share those applications which are in the same group of the browser. Is there any method to share an app whic is open on a different group?

Thanks to everyone who will try to help me

**Comment by tonycpsu** [comment]
https://github.com/qtile/qtile

**Comment by Cela-02** [comment]
what am I supposed to resolve following that link? I couldn't find anything that solved my problem on that so I asked here. Why did you close my issue?

**Comment by tonycpsu** [comment]
You're in the `urwid` project, not `qtile`.

**Comment by Cela-02** [comment]
Sorry, I didn't see that
