### ISSUE TITLE
Relatively high CPU usage when using the asyncio event loop

### ISSUE THREAD

**Issue by NicolasLM** [urwid/urwid#475]
##### Description:

Processes using urwid with the asyncio event loop are very often in the "Running" state even when they are idle, resulting in wasted CPU cycles.

Using `strace` on the process, I tracked it down to a very short event loop timeout of 34 ms.

##### Affected versions (if applicable)
- [X] `master` branch `951093c8ec123`
- [X] Latest stable version from `pypi`

Reproduced on Linux with both Python 3.9.2 and Python 3.7.3.

##### Steps to reproduce (if applicable)

A very simple application that does nothing:

```python
import asyncio

import urwid

txt = urwid.Text('Hello World')
fill = urwid.Filler(txt, 'top')
urwid_main_loop = urwid.MainLoop(
    fill,
    event_loop=urwid.AsyncioEventLoop(loop=asyncio.get_event_loop())
)
urwid_main_loop.run()
```

##### Expected/actual outcome
Actual outcome, a syscall every 34 ms:
```
$ strace -p 62901
strace: Process 62901 attached
epoll_wait(3, [], 3, 29)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
epoll_wait(3, [], 3, 34)                = 0
[...]
```

Expected outcome, a syscall only when something happens:
```
$ strace -p 62967
strace: Process 62967 attached
select(4, [0 3], [], [0 3], NULL
```

**Comment by tonycpsu** [comment]
Possible duplicate of #90

**Comment by NicolasLM** [comment]
I am sorry for the noise, this is definitely a duplicate. The linked commit https://github.com/urwid/urwid/commit/7c8cd1eb683036084c3e31ea6a7712cb98311430 explains the behavior I'm seeing and provides a workaround.
