### ISSUE TITLE
excess.org links don't work

### ISSUE THREAD

**Issue by calvincramer** [urwid/urwid#482]
#### Description:
Links to excess.org/urwid/... are dead links

#### Affected versions (if applicable)
- [ ] latest master (951093c8ec12309e5baa19ee6f907bc35a830f54)

#### Steps to reproduce (if applicable)
```sh
cd <urwid clone>
grep -ri "excess.org"
# Copy a link to web browser (example: https://excess.org/urwid), excess.org gives 404 page.
```

#### Expected/actual outcome
Link to proper locations

**Comment by wardi** [comment]
Working to add the redirect back in. I noticed that the ssl cert for urwid.org wasn't working in the process so I tweaked the dns settings and tried removing and re-adding the custom domain on github pages. Might be fixed in an hour or so.

**Comment by calvincramer** [comment]
Accessing [https://excess.org/urwid](https://excess.org/urwid) now redirects to [https://urwid.org/](https://urwid.org/)
Thanks!
