### ISSUE TITLE
Mouse text selection and link opening not working

### ISSUE THREAD

**Issue by fab-jul** [urwid/urwid#484]
##### Description:
In my normal macOS Terminal view, I can drag my clicked mouse to select text, and I can double click while holding `CMD` to open a link (i.e. something starting with http:// or https://)

This does not work for text in a `urwid.Text` box. In fact, dragging my clicked mouse has no effect, despite `handle_mouse=True`.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
```
  import urwid
  window = urwid.Frame(urwid.Filler(urwid.Text("http://example.com")))
  loop = urwid.MainLoop(window)
  loop.run()
```

##### Expected/actual outcome
Expected: I can CMD+double click on the link to open it in the browser.

**Comment by vapier** [comment]
opening links in your browser is something your terminal does, not urwid.  if you have mouse reporting on, you need to temporarily disable it ("defeat it") before triggering the link opening behavior.

of course, whether your terminal emulator supports link opening, and how it defeats mouse reporting, is completely up to the terminal emulator.  normally the Alt key is used to defeat mouse reporting.

**Comment by AnonymouX47** [comment]
> Alt key is used to defeat mouse reporting.

Just in case someone else sees stumbles upon this, some terminal emulators also use `Ctrl` or `Shift`.

By the way, @penguinolog I think this should be closed as it's not an issue with urwid.

**Comment by penguinolog** [comment]
Duplicate #391
