### ISSUE TITLE
[Question] Is there a way to hide a widget without destroying it?

### ISSUE THREAD

**Issue by Column01** [urwid/urwid#485]
##### Description:
I'm looking for a way to toggle a widget's visibility on-screen without completely deleting it. Is there some way I can do this?

My project has 2 panels that have data updated in them automatically, and I'd like to allow the user to hide them with a keystroke. The only way I could think of was to delete them, but obviously this breaks the code that updates them automatically and isn't really ideal. Is there some sort of way I can toggle their visibility but still allow this code to update their contents so I can make them visible at a later point?

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [ ] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
N/A

##### Expected/actual outcome
N/A

**Comment by tonyc-blastpoint** [comment]
Depends on what the parent widget is.  For `Pile` and `Columns` you can just delete the widget from the container's `contents` and as long as you have a reference to it somewhere else, you can update it and then re-add it to the container's `contents`.

**Comment by tonyc-blastpoint** [comment]
Depends on what the parent widget is. For `Pile` and `Columns` you can just delete the widget from the container's `contents` and as long as you have a reference to it somewhere else, you can update it and then re-add it to the container's `contents`.

**Comment by tonycpsu** [comment]
Depends on what the parent widget is. For `Pile` and `Columns` you can just delete the widget from the container's `contents` and as long as you have a reference to it somewhere else, you can update it and then re-add it to the container's `contents`.

**Comment by Column01** [comment]
Well, the widgets in question are both inside a single `Pile`, and then finally they are both inside a `LineBox`. If I delete them from it, will it not break the code that updates their contents? Ideally, I'd like the **entire** pile to be invisible without actually deleting them.

**Comment by tonyc-blastpoint** [comment]
Sounds like what you want in that case is a [`WidgetPlaceholder`](http://urwid.org/reference/widget.html#urwid.WidgetPlaceholder) inside the `LineBox`, then put the `Pile` inside the `WidgetPlaceholder`.  When you want the `Pile` to go away, replace the `WidgetPlaceholder`'s `original_widget` property with something like `urwid.Filler(urwid.Text(""))`

**Comment by tonycpsu** [comment]
Sounds like what you want in that case is a [`WidgetPlaceholder`](http://urwid.org/reference/widget.html#urwid.WidgetPlaceholder) inside the `LineBox`, then put the `Pile` inside the `WidgetPlaceholder`.  When you want the `Pile` to go away, replace the `WidgetPlaceholder`'s `original_widget` property with something like `urwid.Filler(urwid.Text(""))`

**Comment by Column01** [comment]
It's basically this hierarchy:

- Pile
    - LineBox
        - Text
    - LineBox
        - Custom widget wrapper (WidgetPlaceholder)
            - ListBox
                - SimpleListWalker
                
The Text box is updated using a direct reference to it and calling `set_text()`

The ListBox has it's contents updated by updating the SimpleListWalker's contents

**Comment by Column01** [comment]
Here is an example, but I would like this whole pile to go away and for the console on the left to expand and take its place
![cOoNv7dqlb](https://user-images.githubusercontent.com/26526649/133470666-17e8b02c-5495-488d-a4c1-7c6f171def3b.png)

**Comment by tonyc-blastpoint** [comment]
Looks like the container widget there is `Columns`, not `Pile`.

In this case, it's what I said originally.  You want a `Columns` widget with 2 columns, then you want one column.  So just keep a reference to the `Pile` in the 2nd column inside the containing widget, update it as necessary, etc. then add it to the `contents` of the `Columns`.  When you want to hide it, delete it from the contents., then when you want to re-add it, insert it into the list again.

**Comment by tonycpsu** [comment]
Looks like the container widget there is `Columns`, not `Pile`.

In this case, it's what I said originally.  You want a `Columns` widget with 2 columns, then you want one column.  So just keep a reference to the `Pile` in the 2nd column inside the containing widget, update it as necessary, etc. then add it to the `contents` of the `Columns`.  When you want to hide it, delete it from the contents., then when you want to re-add it, insert it into the list again.

**Comment by Column01** [comment]
> Looks like the container widget there is `Columns`, not `Pile`.

It isn't a `Columns` widget, the console window is, but the sidebar is not.

```python
g_sidebar = urwid.Pile((
        ('pack', urwid.AttrMap(urwid.LineBox(self.g_stats, title='stats'), 'stats')),
        urwid.AttrMap(urwid.LineBox(self.g_pmenu, title="players"), 'menu')))
g_main = urwid.Columns((
        urwid.WidgetDisable(urwid.AttrMap(self.g_output_wrap, 'console')),
        ('fixed', 31, g_sidebar)))
```

**Comment by Column01** [comment]
Ohhhh I see now

**Comment by tonycpsu** [comment]
Looks something like this:

https://github.com/tonycpsu/panwid/blob/unstable/panwid/autocomplete.py#L270

**Comment by Column01** [comment]
So what I'd need to do is keep my reference to `g_sidebar` and `g_main` and then when I want to hide the sidebar, remove the second column and when I want it back, add it to the column again?

**Comment by Column01** [comment]
That appears to have worked! Thank you so much 😄
