### ISSUE TITLE
Terminal session not properly restored upon exit

### ISSUE THREAD

**Issue by razed-mum** [urwid/urwid#487]
##### Description:
I executed the programs in `master/examples/` directory. Turns out, Urwid does not properly restore terminal session upon exit. Output from other commands afterwards do clear the terminal window, so it's not as if it's left in an irreparable state. In fact, the `clear` command completely clears the mess. But it's a bug nevertheless.

![image](https://user-images.githubusercontent.com/66983935/141300304-9d899d04-731c-41e4-b860-195748666808.png)
![image](https://user-images.githubusercontent.com/66983935/141304751-841c7447-705a-4d02-8ef3-0bf15c26b238.png)

##### Affected versions
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce
I'm using an xterm-256color emulator natively provided by the Ubuntu distro on WSL. I'm running them using Python 3.8.10 (inside a virtual environment, if that's relevant). Running the program from [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) produces the same issue.

![image](https://user-images.githubusercontent.com/66983935/141307704-c5f71e11-b5bd-44a7-9939-baa9571e4416.png)

**Comment by vapier** [comment]
urwid relies on using the alternate screen.  if your terminal doesn't support that, or the app you're using disables it, you'll see this behavior.  unfortunate, but expected.

**Comment by AnonymouX47** [comment]
#556 should fix this. Also, see my comments in #521.
