### ISSUE TITLE
Ellipsis wrap mode is supported only for UTF and limited list of other encodings

### ISSUE THREAD

**Issue by kulkarniniraj** [urwid/urwid#496]
In case of unsupported encoding, error will happen (text layout can not be correctly built).

**Supported encodings**:
- big5
- big5hkscs
- cp874
- cp932
- cp949
- cp950
- cp1250
- cp1251
- cp1252
- cp1253
- cp1254
- cp1255
- cp1256
- cp1257
- cp1258
- euc_jp
- euc_jis_2004
- euc_jisx0213
- euc_kr
- gb2312
- gbk
- gb18030
- hz
- iso2022_jp
- iso2022_jp_1
- iso2022_jp_2
- iso2022_jp_2004
- iso2022_jp_3
- iso2022_jp_ext
- iso2022_kr
- johab
- koi8_t
- kz1048
- mac_cyrillic
- mac_greek
- mac_iceland
- mac_latin2
- mac_roman
- mac_turkish
- ptcp154
- shift_jis
- shift_jis_2004
- shift_jisx0213
- utf_32
- utf_32_be
- utf_32_le
- utf_16
- utf_16_be
- utf_16_le
- utf_7
- utf_8
- utf_8_sig

**Unsupported encodings**:
- ascii
- cp037
- cp273
- cp424
- cp437
- cp500
- cp720
- cp737
- cp775
- cp850
- cp852
- cp855
- cp856
- cp857
- cp858
- cp860
- cp861
- cp862
- cp863
- cp864
- cp865
- cp866
- cp869
- cp875
- cp1006
- cp1026
- cp1125
- cp1140
- latin_1
- iso8859_2
- iso8859_3
- iso8859_4
- iso8859_5
- iso8859_6
- iso8859_7
- iso8859_8
- iso8859_9
- iso8859_10
- iso8859_11
- iso8859_13
- iso8859_14
- iso8859_15
- iso8859_16
- koi8_r
- koi8_u

**Comment by tonycpsu** [comment]
Can't reproduce this one with Urwid 2.1.2:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/914142/151706071-8e3ee03a-cf8b-455d-9978-10b6bd5022f4.png">

**Comment by kulkarniniraj** [comment]
Failing for me on all fonts. I am using UTF-8. Somehow it takes 3 bytes to encode '…' on my system.

**Comment by penguinolog** [comment]
Can not reproduce with actual `master` branch:
```python
>>> from __future__ import annotations
>>> import urwid
>>> t = urwid.Text('abcd'*31, wrap = urwid.ELLIPSIS)
>>> w = urwid.Filler(t)
>>> w.sizing()
{'box'}
>>> w.render((20, 20))
<urwid.canvas.CompositeCanvas at 0x7f7b6cab31f0>
>>> w.render((20, 20)).text 
[b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'abcdabcdabcdabcdabc\xe2\x80\xa6',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ',
 b'                    ']
>>> print(repr(b'\n'.join(w.render((5, 10)).text).decode()))
'     \n     \n     \n     \nabcd…\n     \n     \n     \n     \n     '
```
Ellipsis is correctly rendered too
