### ISSUE TITLE
AttributeError: 'int' object has no attribute 'selectable' when using 

### ISSUE THREAD

**Issue by Gcat101** [urwid/urwid#498]
##### Description:
I get this error:
`AttributeError: 'int' object has no attribute 'selectable'`
When I try to:
```python3
mainscreen = urwid.Columns((
        urwid.Text('NEWS'),
        urwid.Text('RANDOM TUI/CLI')
))

loop = urwid.MainLoop(urwid.Filler(mainscreen))
loop.run()
```

##### Affected versions
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce
1. Copy code
2. Paste
3. Run

##### Expected/actual outcome
Display columns

**Comment by tonyc-blastpoint** [comment]
Can't reproduce with Urwid 2.1.2:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/68251640/154143405-4d05ee18-d50a-4500-b991-3104824b5196.png">

**Comment by tonycpsu** [comment]
Can't reproduce with Urwid 2.1.2:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/914142/154143574-3b0490cd-c77f-4eb4-bdec-cccb933a04bf.png">
