### ISSUE TITLE
The following errors always occur when I use urwid.Pile()

### ISSUE THREAD

**Issue by wuyanpinguniontech** [urwid/urwid#519]
## code
```python
import urwid

header = urwid.Text("Header")
footer = urwid.Text("Footer")

pile = urwid.Pile([header,footer])

urwid.MainLoop(pile).run()
```
## Issue
![image](https://user-images.githubusercontent.com/103416248/218011028-9b092a53-5a74-44c5-97e3-35e74b580dd7.png)

**Comment by tonycpsu** [comment]
See https://github.com/urwid/urwid/wiki/FAQ

Wrap the Text elements in an `urwid.Filler(...)` then put them in the Pile.
