### ISSUE TITLE
Unable to install urwid from PyPI successfully

### ISSUE THREAD

**Issue by springcomp** [urwid/urwid#520]
##### Description:

The latest stable version from `pypi` cannot be installed successfully on the first try.
It fails with a `invalid command bdist_wheel` error.

On the next try, it installs successfully.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)

- Install and upgrade `setuptools` and `wheel` to their latest versions.
- Create a new empty folder.
- Add a `requirements.txt` file with the following contents:

```
wheel==0.38.4
urwid==2.1.2
```

- Initialize a new virtual environment `` python -m venv . `` in this folder.
- Activate the virtual environment `` source bin/activate ``.
- Either installing the requirements or building wheels directly fail:

```sh
pip install -r requirements.txt
```

##### Expected/actual outcome

Installing should succeed on the first try.

**Comment by AnonymouX47** [comment]
Just passing by...

Seems the problem might be specific to your environment cos I just followed your steps and couldn't reproduce this.

**Comment by springcomp** [comment]
@AnonymouX47 

Thanks.
