### ISSUE TITLE
raw display and background

### ISSUE THREAD

**Issue by oliver-sanders** [urwid/urwid#521]
##### Description:

Moving an app into the background (i.e. ctrl+z) doesn't work nicely with the raw display.

Here's a demo using the [pallet_test](http://urwid.org/examples/index.html#palette-test-py) example:

![Screenshot from 2023-03-22 18-08-45](https://user-images.githubusercontent.com/16705946/226998484-9b886c9c-b2f9-407c-ba52-5c69baa658a3.png)

And here's what happens when I ctrl+z the terminal:

![Screenshot from 2023-03-22 18-08-55](https://user-images.githubusercontent.com/16705946/226998488-ce363140-d9d0-4a6d-8759-09b1c96ec592.png)

This appears to be a regression of https://github.com/urwid/urwid/issues/25 which reported a very similar issue. This doesn't happen with the curses display.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
- Open a raw-display app.
- Press ctrl+z

Reproduced with xterm-256color / Linux.

##### Expected/actual outcome
- The app should background cleanly leaving the terminal available for other activities.

**Comment by AnonymouX47** [comment]
Just for the record, this is completely unrelated to the signal `SIGTSTP` (or any signal at all). It's a result of the escape sequence used by urwid to switch back to the normal screen buffer. Also, the same issue occurs when quitting (i.e stopping the main loop) normally.

I had actually encountered this sometime back and simply used the appropriate escape sequence before and after the `loop.run()` but unfortunately that didn't and wouldn't cover the case of suspending the process with `Ctrl + z`.

I've opened a PR that fixes this.

**Comment by AnonymouX47** [comment]
@oliver-sanders If you need a fix pending the time the version of urwid including this fix is released, I'll suggest overriding `Screen._start()` and `Screen._stop()` and writing the escape sequences used in my PR via `Screen.write()`.

Note that the order of writing each escape sequence and calling the overridden method is important... In `_start()`, the former should come first but in `_stop()`, the latter should come first.
