### ISSUE TITLE
consider switching to a urwid org?

### ISSUE THREAD

**Issue by techdragon** [urwid/urwid#53]
using a github org would make it look more official, and be better for the creation of dependent tools e.g. an 'urwid-extras' package etc. 

I'd recommend this for after #41 is resolved.

**Comment by techtonik** [comment]
There is already http://urwid.org, so what all this is about?

**Comment by wardi** [comment]
This is about moving the repo to https://github.com/urwid/ which I should just go ahead with.

**Comment by techtonik** [comment]
Ahh.. I see. =) Then take this - https://github.com/urwid/urwid/pull/167
