### ISSUE TITLE
Recent commit breaks apps that rely on old versioning scheme

### ISSUE THREAD

**Issue by danschwarz** [urwid/urwid#567]
In the [toot](https://github.com/ihabunek/toot) app we have the requirements.txt dependency for urwid-

`urwid>=2.0.0,<3.0`

Worked fine until the recent change https://github.com/urwid/urwid/commit/8d8e4b678cc0f93149a4a964b26ee11fb136ea0f

Now the version string in master is quite different and <2.0.0.

Is this intentional?

**Comment by penguinolog** [comment]
```
(bug_validation) alekseis@1857be7-lcelt:~$ pip install -U "git+https://github.com/urwid/urwid"
Collecting git+https://github.com/urwid/urwid
  Cloning https://github.com/urwid/urwid to /tmp/pip-req-build-aq0gs5xr
  Running command git clone --filter=blob:none --quiet https://github.com/urwid/urwid /tmp/pip-req-build-aq0gs5xr
  Resolved https://github.com/urwid/urwid to commit 30adceb5ce8b4136d865245a4b3b59fa00dc13db
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: urwid
  Building wheel for urwid (pyproject.toml) ... done
  Created wheel for urwid: filename=urwid-2.1.3.dev66+g30adceb-cp310-cp310-linux_x86_64.whl size=277749 sha256=de128661f3cad9beb18673db27fff2c25dda57dfb185f8a31af332d427ec4304
  Stored in directory: /tmp/pip-ephem-wheel-cache-qtxy79jc/wheels/2a/93/00/01213829ea3dda62dc0addfcb952fdce94e9a1cef2ea95fff0
Successfully built urwid
Installing collected packages: urwid
Successfully installed urwid-2.1.3.dev66+g30adceb
(bug_validation) alekseis@1857be7-lcelt:~$ python -m IPython
Python 3.10.7 (main, May 29 2023, 13:51:48) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.13.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import urwid

In [2]: urwid.__version__
Out[2]: '2.1.3.dev66+g30adceb'

In [3]: import importlib.metadata

In [4]: distro = importlib.metadata.distribution('urwid')

In [5]: distro.version
Out[5]: '2.1.3.dev66+g30adceb'
```

**Comment by wardi** [comment]
@danschwarz `2.1.3.dev66+g30adceb` is considered as `<2.0.0`?

**Comment by danschwarz** [comment]
That's not the version string I was seeing. The one I saw was 0.1... something. I may have been using an incorrect method to install urwid. I'm currently away from my dev box but when I have a chance I'll report exactly what I saw, and try installing with pip -U

**Comment by penguinolog** [comment]
SCM based versioning require SCM info. If no tags visible (like you have a fork without upstream link or downloaded and transferred without `.git` folder) - it will use fallback version (0.0.1).
For installation on fully isolated machine I'm using wheel packages (`python -m build` is the most modern way to build, previous was `pip wheel` and oldest, now deprecated, was `python setup.py bdist_wheel`)

**Comment by danschwarz** [comment]
Ok that must be it. I was building with python setup.py...  I'll try another way when I get online
