### ISSUE TITLE
new release for #554

### ISSUE THREAD

**Issue by jacekpoz** [urwid/urwid#568]
hey, could you make a new release to get rid of https://github.com/urwid/urwid/issues/554?

**Comment by penguinolog** [comment]
Package build CI/CD addition (manyLinux) will be done on Monday.
Packages publishing can be done by @wardi as owner

**Comment by penguinolog** [comment]
Released 2.2.0.
For common Linux and MacOS architectures and interpreters provided binary packages (no compilation required)
