### ISSUE TITLE
PR #541 is making the toot client stall at startup until a keyboard or mouse event is received

### ISSUE THREAD

**Issue by danschwarz** [urwid/urwid#575]
##### Description:
toot relies on asyncio and does a lot of async network access, especially at startup.  

When running with Urwid release 2.1.2 up to master right before #541 was integrated, starting up toot takes about 6sec to get from title screen to fully loaded timeline, and it does this without any user input.

When running on urwid master,  350ee5c47ff565d3b0d25b1c3cbddbfb2a0a2a4f or later, startup stalls on the title screen showing "Loading..." indefinitely if no keyboard/mouse activity.  If there is keyboard or mouse activity at startup, toot takes about 6sec to get from title screen to fully loaded timeline, as above.

I'm not sure whether this is an issue with the PR, or an issue with how toot is using asyncio;  I'm not very familiar with Python asyncio details.  Including @ihabunek as he may have some insight.

##### Affected versions (if applicable)
- [X] `master` branch (specify commit) 350ee5c47ff565d3b0d25b1c3cbddbfb2a0a2a4f 
- [ ] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)

You want to test against a [special version of toot](https://github.com/danschwarz/toot/tree/urwid_test2).  This is the current master with one line of code commented out - it removes the BigText name/version number display on the title screen (you'll need my version to run without crashing on Urwid master versions prior to integration of #555 )

##### Expected/actual outcome

When run with Urwid 2.1.2 release, or any version of master prior to 350ee5c47ff565d3b0d25b1c3cbddbfb2a0a2a4f , toot does not stall, it proceeds from title screen  to the fully loaded timeline within 6 seconds.

When run with 350ee5c47ff565d3b0d25b1c3cbddbfb2a0a2a4f  or later versions of master, toot stalls at "loading..." indefinitely, until a keyboard/mouse event is received.

**Comment by danschwarz** [comment]
Updated the title and description to reflect what's really going on here.

**Comment by penguinolog** [comment]
Looks like I'll have to return old behavior and put current asyncio logic for more investigation

**Comment by danschwarz** [comment]
Thanks for looking into this.

**Comment by penguinolog** [comment]
I agree, but at this moment looks like screen not redrawed if no input events (and widgets invalidated). This is blocker

**Comment by wardi** [comment]
With other event loops if you make a change to the widgets not related to input or a timer urwid is aware of you're responsible for calling draw_screen. I think it's reasonable to expect the same of asyncio users.

**Comment by penguinolog** [comment]
You are correct and I'll try to re-run our code with asyncio loop to see how it will work (we have in-place replacing widgets by timer and keyboard/mouse interaction + network wait)

**Comment by danschwarz** [comment]
Although I don't have a deep understanding of asyncio, I think that the issue I've found with toot might be more than adding in a few missing calls to `draw_screen()` . Tagging @ihabunek for his input on this issue:

Have a look at[ toot's `run()` method](https://github.com/danschwarz/toot/blob/0662a7616bc2027c2b71cab9084be2dd576110cd/toot/tui/app.py#L128):
```
   def run(self):
        self.loop.set_alarm_in(0, lambda *args: self.async_load_instance())
        self.loop.set_alarm_in(0, lambda *args: self.async_load_followed_accounts())
        self.loop.set_alarm_in(0, lambda *args: self.async_load_followed_tags())
        self.loop.set_alarm_in(0, lambda *args: self.async_load_timeline(
            is_initial=True, timeline_name="home"))
        self.loop.run()
        self.executor.shutdown(wait=False)
```
Alarms are set to trigger async loading of various data from a Mastodon server.
`async_load_timeline`, the final one, instantiates a Timeline object that will redraw the screen with new widgets, a tlimeline list and so forth. This never happens.

Here is `async_load_timeline`

**Comment by wardi** [comment]
@danschwarz yes if your `set_alarm_in(0, ...)` arguments aren't getting called until input is received then that does sound like a new bug.

**Comment by danschwarz** [comment]
Bug is still present in 2.2.1 :( any help would be appreciated, or we'll have to start looking into replacing our use of asyncio.

**Comment by wardi** [comment]
@danschwarz is this code updating UI elements from a different thread? That could definitely cause problems including not updating the screen or even crashing while redrawing.

It would be really helpful to have a smaller example that demonstrates the issue.

**Comment by penguinolog** [comment]
Putting mass debug logs showing, that `AsyncIOEventLoop` is not async at all: all timers are blocked while waiting for input.
IMHO need to spend time for real `asyncio` usage implementation, because sync code in async always blocking. And this change maybe API breaking.

**Comment by penguinolog** [comment]
Found fully working solution with asyncio:
`self.executor.submit` in example submit job in another thread and it can not properly submit future to the asyncio task in current thread.
Synthetic example without urwid:
```python
from __future__ import annotations

import asyncio
import time
from concurrent.futures import ThreadPoolExecutor, Future


class Loop:
    def __init__(self, loop: asyncio.AbstractEventLoop):
        self._loop = loop
        self.executor = ThreadPoolExecutor()
        self.start_time: float = 0.

    def __call__(self) -> None:
        if not self._loop.is_running():
            print("Loop is not started")
            return

        self.start_time = time.time()
        self._loop.call_later(0, self.load_async)

    def load_async(self):
        print(f"Submit first call: {time.time() - self.start_time}")
        self.executor.submit(self.first).add_done_callback(self.first_cb)
        self._loop.call_later(3, self.submit_directly)

    def first(self):
        print(f"First TimerHandle called: {time.time() - self.start_time}")

    def first_cb(self, future: Future) -> None:
        print(f"First callback called: {time.time() - self.start_time}")
        self._loop.call_later(0, self.second)

    def second(self) -> None:
        print(f"Second TimerHandle called: {time.time() - self.start_time}")

    def submit_directly(self):
        print(f"Submitted directly called: {time.time() - self.start_time}")


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.call_soon(Loop(loop))
    loop.call_later(5, loop.stop)
    loop.run_forever()
    loop.stop()
```
produce:
```
Submit first call: 0.00010800361633300781
First TimerHandle called: 0.0005550384521484375
First callback called: 0.0008044242858886719
Second TimerHandle called: 3.003976583480835
Submitted directly called: 3.0041160583496094
```

Need to use `run_in_executor` method of event loop:
```python
from __future__ import annotations

import asyncio
import time
from concurrent.futures import ThreadPoolExecutor, Future


class Loop:
    def __init__(self, loop: asyncio.AbstractEventLoop):
        self._loop = loop
        self.executor = ThreadPoolExecutor()
        self.start_time: float = 0.

    def __call__(self) -> None:
        if not self._loop.is_running():
            print("Loop is not started")
            return

        self.start_time = time.time()
        self._loop.call_later(0, self.load_async)

    def load_async(self):
        print(f"Submit first call: {time.time() - self.start_time}")
        self._loop.run_in_executor(self.executor, self.first).add_done_callback(self.first_cb)
        # self.executor.submit(self.first).add_done_callback(self.first_cb)
        self._loop.call_later(3, self.submit_directly)

    def first(self):
        print(f"First TimerHandle called: {time.time() - self.start_time}")

    def first_cb(self, future: Future) -> None:
        print(f"First callback called: {time.time() - self.start_time}")
        self._loop.call_later(0, self.second)

    def second(self) -> None:
        print(f"Second TimerHandle called: {time.time() - self.start_time}")

    def submit_directly(self):
        print(f"Submitted directly called: {time.time() - self.start_time}")


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.call_soon(Loop(loop))
    loop.call_later(5, loop.stop)
    loop.run_forever()
    loop.stop()
```

Then everything works as expected:
```
Submit first call: 0.00010728836059570312
First TimerHandle called: 0.0005779266357421875
First callback called: 0.0008931159973144531
Second TimerHandle called: 0.0010387897491455078
Submitted directly called: 3.0033955574035645
```

API extension for urwid will be done soon.
