### ISSUE TITLE
Newlines for each screen.start()/stop() call

### ISSUE THREAD

**Issue by scopatz** [urwid/urwid#60]
First off thanks for the awesome library!

I am seeing a newline in the terminal for each start and stop call I insert and I have no way to get rid of them.  Using the edit.py example:

``` bash
scopatz@ares ~/xo/xo master $ python3 edit.py main_save.py

scopatz@ares ~/xo/xo master $ 
```

If I insert 

``` python
self.loop.screen.start()
self.loop.screen.stop()
```

right before the `self.loop.run()` call, I get another blank line for each start/stop pair.

Is there some way to get rid of this and preserve my precious vertical space?  Looking through the urwid source it wasn't obvious where this is coming from  The behaviour is also there in Python 2.

**Comment by asmeurer** [comment]
This has broken the screen clearing in PuDB. See https://github.com/inducer/pudb/issues/149. What is the best way to get the old behavior back?

**Comment by wardi** [comment]
@asmeurer huh. really? you need the newline for the screen to be restored properly?

I'm open to suggestions! Does it work if you send a '\n' to the terminal yourself after calling stop()?

**Comment by asmeurer** [comment]
It doesn't seem to. 

I don't know why this is the case. I just bisected the issue to this commit.

**Comment by wardi** [comment]
@asmeurer please try the fix in 7907e856bb2e44fbcdeac765b2470a359596a4e1 (now on master)

**Comment by asmeurer** [comment]
Sorry, it looks like it still has the issue. Changing that `\r` to a `\n` fixes it.

**Comment by asmeurer** [comment]
By the way, urwid is broken in Python 3 because of https://github.com/wardi/urwid/issues/110.

**Comment by wardi** [comment]
@asmeurer drat. well, we could do something more horrible, like send a \n then move the cursor up one space.

**Comment by asmeurer** [comment]
Again, I have no idea how any of this works (and I didn't write the uwrid code in pudb). I only know that one commit works and one doesn't. It's possible we are doing something wrong in pudb. 

Maybe this should be a keyword argument. 

We do hope to remove the screen switching in pudb (see https://github.com/inducer/pudb/issues/48), but  it requires a bit of work. Assumedly if we do that this issue would not be a problem any more.

**Comment by winbornejw** [comment]
@asmeurer I would actually be curious to see if you'd still see the issue I was seeing that the \r fixed for me. You could see it with the test script I provided in the first response of wardi/urwid#127. When I suggested the fix, I wasn't completely sure if it would work in every case. I'm not having an issue with pudb that I can find using the current master of urwid and pudb from pip. I'm also running it on Fedora with lxterminal and konsole.

**Comment by winbornejw** [comment]
@asmeurer I think I did just find something else for you to try, also in raw_display.py. Instead of sending a newline or carriage return to have the terminal try and update, that's what sys.stdout.flush() is meant to be used for and the flush method is already using. This is working for me, perhaps it'll also work with terminal.app.
```python
        self.write(
            self._attrspec_to_escape(AttrSpec('',''))
            + escape.SI
            + move_cursor
            + escape.SHOW_CURSOR)

        self.flush()
```

**Comment by asmeurer** [comment]
Calling self.flush() seems to fix it.
