### ISSUE TITLE
[Question] Has asyncio event loop usage changed since version 2.2.0? 

### ISSUE THREAD

**Issue by lunar-mining** [urwid/urwid#665]
In urwid versions 2.1.1 and earlier I could create an async task that runs in the background and continuously updates the screen, like so:

```
import urwid, asyncio

class Demo:
    palette = [('body','light gray','black', 'standout')]

    def __init__(self, data=None):
        self.listbox_content = []
        self.listwalker = urwid.SimpleListWalker(self.listbox_content)
        self.list = urwid.ListBox(self.listwalker)
        self.ui = urwid.Frame(urwid.AttrWrap( self.list, 'body' ))

        self.ev = asyncio.new_event_loop()
        asyncio.set_event_loop(self.ev)

    def main(self):
        self.loop = urwid.MainLoop(self.ui, self.palette,
            event_loop=urwid.AsyncioEventLoop(loop=self.ev),
                                   unhandled_input=self.unhandled_input)
        self.ev.create_task(self.say_hello())
        self.loop.run()

    def unhandled_input(self, k):
        if k in ('q','Q'):
            raise urwid.ExitMainLoop()

    async def say_hello(self):
        while True:
            await asyncio.sleep(0.1)
            self.listwalker.contents.append(urwid.Text("hello"))
 

if __name__ == '__main__':
    demo = Demo()
    demo.main()
```

In the new releases, the messages created by the async task do not render on the screen unless I physically select the terminal with my mouse.

Perhaps it is related to this breaking change: https://github.com/urwid/urwid/pull/541. Would appreciate any guidance on the new usage, if any.

**Steps to reproduce:**

Run the above code on version 2.1.1 and version 2.2.0 and compare outcomes.

**Note:**

I have tested this using `sv` terminal on dwm and `kitty` terminal on i3.

**Comment by ulidtko** [comment]
@lunar-mining try adding `self.ev.call_soon(self.loop.draw_screen)` in the loop of `say_hello()` after listbox contents update. #418 explains this more clearly.

**Comment by lunar-mining** [comment]
Works like a charm, thanks @ulidtko!
