### ISSUE TITLE
[BUG] problem with unicode chars

### ISSUE THREAD

**Issue by petaflot** [urwid/urwid#678]
##### Description:
can't display braille characters

##### Affected versions (if applicable)
2.2.3

##### Steps to reproduce (if applicable)
```
import urwid
from time import sleep

braille = "⠎⢖⠞⠞⢾⠄⣿⠄⣶⢾⡦⠞⠖"
print(braille)
sleep(1)

txt = urwid.Text(braille)
fill = urwid.Filler(txt, 'top')
loop = urwid.MainLoop(fill)
loop.run()
```

##### Expected/actual outcome
display `⠎⢖⠞⠞⢾⠄⣿⠄⣶⢾⡦⠞⠖` instead of something that looks like 

```
`??[38;2;0;255;114m?■??[0m???[38;2;0;255;96m?■??[0m???[38;2;0;255;137m?■??[0m???[38;2;0;255;137m?■??[0m???[38;2;0;255;156m?■??[0m???[38;2;255;192;0m?■??[0m???[38;2;255;0;0m?■??[0m???[38;2;255;192;0m?■??[0m???[38;2;0;255;203m?■??[0m???[38;2;0;255;156m?■??[0m???[38;2;0;255;174m?■??[0m???[38;2;0;255;137m?■??[0m???[38;2;0;255;90m?■??[0m?`
```

the above output was copied from console (because I can't select and copy text in terminology), but in terminology I actually have braille symbols where there are squares here ; it seems my console does not have an appropriate font

**Comment by penguinolog** [comment]
I see strange conversion in your code:
```python
braille = bab.to_braille("⠎⢖⠞⠞⢾⠄⣿⠄⣶⢾⡦⠞⠖")
```
`bab` is not in imports and not python keyword.
Without this conversion:
```python
from __future__ import annotations

import urwid

txt = urwid.Text("⠎⢖⠞⠞⢾⠄⣿⠄⣶⢾⡦⠞⠖")
fill = urwid.Filler(txt, 'top')
loop = urwid.MainLoop(fill)
loop.run()
```
Produce:
![image](https://github.com/urwid/urwid/assets/16033331/a1b3540f-3706-496b-830a-79933f89075c)
(Screenshot of alacritty terminal, locale: `en_US.UTF-8`)

**Comment by petaflot** [comment]
fixed typo (see first post)

will try with a different term...

**Comment by penguinolog** [comment]
Re-tried with `xterm`, `urxvt`, VTE based (guake & gnome-terminal) - all displayed correctly.
