### ISSUE TITLE
[BUG] python3 setup.py is not installing any .py file

### ISSUE THREAD

**Issue by O-ring** [urwid/urwid#682]
##### Description:

python3 setup.py is not installing any py files in site-packages/urwid
Only the str_util.cpython-39-x86_64-linux-gnu.so is copied.

OS is Slackware Linux 15 (64 bit)

##### Affected versions (if applicable)

https://pypi.org/packages/source/u/urwid/urwid-2.2.3.tar.gz

##### Steps to reproduce (if applicable)

python3 setup.py install --root=/tmp/ur223

running install
running build
running build_ext
building 'urwid.str_util' extension
creating build
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/source
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/python3.9 -c source/str_util.c -o build/temp.linux-x86_64-3.9/source/str_util.o
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/urwid
gcc -pthread -shared build/temp.linux-x86_64-3.9/source/str_util.o -L/usr/lib64 -o build/lib.linux-x86_64-3.9/urwid/str_util.cpython-39-x86_64-linux-gnu.so
running install_lib
creating /tmp/ur223
creating /tmp/ur223/usr
creating /tmp/ur223/usr/lib64
creating /tmp/ur223/usr/lib64/python3.9
creating /tmp/ur223/usr/lib64/python3.9/site-packages
creating /tmp/ur223/usr/lib64/python3.9/site-packages/urwid
copying build/lib.linux-x86_64-3.9/urwid/str_util.cpython-39-x86_64-linux-gnu.so -> /tmp/ur223/usr/lib64/python3.9/site-packages/urwid
running install_egg_info
running egg_info
writing urwid.egg-info/PKG-INFO
writing dependency_links to urwid.egg-info/dependency_links.txt
deleting urwid.egg-info/requires.txt
writing top-level names to urwid.egg-info/top_level.txt
reading manifest file 'urwid.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGELOG'
adding license file 'COPYING'
writing manifest file 'urwid.egg-info/SOURCES.txt'
Copying urwid.egg-info to /tmp/ur223/usr/lib64/python3.9/site-packages/urwid-2.2.3-py3.9.egg-info
running install_scripts

ls -l /tmp/ur223/usr/lib64/python3.9/site-packages/urwid
total 48
-rwxr-xr-x 1 marco users 47264 Nov 27 16:09 str_util.cpython-39-x86_64-linux-gnu.so*

**Comment by penguinolog** [comment]
`setup.py` is officially deprecated by python packaging and used only for dynamic C extensions handling. In the future this file can be removed.
Please try `pip install` instead. It should also work with precompiled wheel package

**Comment by O-ring** [comment]
Hello Alexey,

thanks for the response.

I'm going to close this issue.
