### ISSUE TITLE
[docs] fail to build docs due to can not find urwid/version.py

### ISSUE THREAD

**Issue by yuzibo** [urwid/urwid#725]
##### Description:
hi, 

I am packaging the urwid to 2.3.4, but when to try to build docs:

```python
  debian/rules execute_after_dh_auto_build
make[1]: Entering directory '/<<PKGBUILDDIR>>'
PYTHONPATH=. http_proxy='127.0.0.1:9' python3 -m sphinx -N -bhtml docs build/html # HTML generator
Running Sphinx v7.2.6

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 358, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/docs/conf.py", line 67, in <module>
    execfile(VERSION_MODULE, VERSION_VARS)
  File "/<<PKGBUILDDIR>>/docs/conf.py", line 64, in execfile
    with open(module) as f:
         ^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/<<PKGBUILDDIR>>/urwid/version.py'

```
I think we must forget something here
##### Affected versions (if applicable)
2.3.4

**Comment by yuzibo** [comment]
sorry for the noisy.
 I am not right to build the package on Debian. On 2.3.4, it needs `python3-setuptools-scm-git-archive` package to generate the `version.py` IIRC. So the issue should be not exist. :)

But BTW, it breaks -doc package if we depends github plugin:

```
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -31,10 +31,10 @@
     'sphinx.ext.todo',
     'sphinx.ext.coverage',
     'sphinx.ext.githubpages',
-    "sphinx_github_changelog",
+    #"sphinx_github_changelog",
 ]

-sphinx_github_changelog_token = os.environ.get("SPHINX_GITHUB_CHANGELOG_TOKEN")
+#sphinx_github_changelog_token = os.environ.get("SPHINX_GITHUB_CHANGELOG_TOKEN")


```

**Comment by penguinolog** [comment]
Technically better to get built HTML documentation from gh-pages branch and built python packages as WHL files from PYPI (since it contains precompiled code)

**Comment by penguinolog** [comment]
Also about git archive: looks like build is done not using `build` or `pip`, because PEP517 should normally create isolated build environment (if opposite not requested explicit) and `setuptools-scm` should be modern enough (>=7.0).
`setuptools-scm-git-archive` is officially deprecated.

**Comment by penguinolog** [comment]
For version 2.3.4 you need tag 2.3.4-docs

**Comment by yuzibo** [comment]
> For version 2.3.4 you need tag 2.3.4-docs

Thanks. But for distro package, maybe only one source tar is more maintainance.
