### ISSUE TITLE
Release 2.4.3 breaks rendering [BUG]

### ISSUE THREAD

**Issue by markqvist** [urwid/urwid#753]
##### Description:

The latest stable release, `2.4.3` breaks layout of several different widgets, including filler and overlay. See below examples.

Is this intended behavior? I'm a bit confused if a point-release like this is intended to alter rendering so significantly, which is why I am currently filing this as a bug. But please do correct me if I am missing something here.

I had to pin [Nomad Network](https://github.com/markqvist/NomadNet) to version `2.4.2` for now to avoid this.

##### Affects
- [x] Latest stable version from `pypi`

##### Example 1 in Urwid 2.4.2 (correct)
![Urwid_2 4 2_1](https://github.com/urwid/urwid/assets/1438012/7a65c3fd-101f-433c-ad5f-28d08b98d33b)

##### Example 1 in Urwid 2.4.3 (incorrect)
![Urwid_2 4 3_1](https://github.com/urwid/urwid/assets/1438012/307ce90d-9632-401e-afac-80864dbb0ff8)

##### Example 2 in Urwid 2.4.2 (correct)
![Urwid_2 4 2_2](https://github.com/urwid/urwid/assets/1438012/f4ff49b0-d829-4cff-98c0-cb19d773ef9f)

##### Example 2 in Urwid 2.4.3 (incorrect)
![Urwid_2 4 3_2](https://github.com/urwid/urwid/assets/1438012/af2e1b1f-087a-426f-aa55-c5d21fd4b341)

**Comment by penguinolog** [comment]
Example 1: Issue confirmed, fix & test ready.
Issue in `Columns` widget with `BOX` column not marked as `BOX` and sizing calculation as box (fully valid sizing and render case, not enough good covered by unittests).
Example 2: checking for details.

**Comment by markqvist** [comment]
Awesome fast fix! Thank you!
