### ISSUE TITLE
Italicizing Text

### ISSUE THREAD

**Issue by ids1024** [urwid/urwid#83]
Urwid allows for making text bold or underlined, but as far as I can tell does not allow for italics. Is it possible to make text italicized in urwid and if not, could it be added in a future version?

I apologize if I'm missing something obvious.

**Comment by wardi** [comment]
AFAIK italic text isn't supported in most terminals I'm aware of. closing this issue for now, but please reopen if you know a way to do that.

**Comment by ids1024** [comment]
Quick tests show that italics work in urxvt, st, xterm, and gnome-terminal.  I presume many others support italics too.  It may not be universal, but it is hardly an obscure feature.  I tested with this command:

```
echo "\e[3mHello World\e[23m"
```

**Comment by wardi** [comment]
That's great! we should absolutely add support for italics

**Comment by lengstrom** [comment]
I'm somewhat interested in helping add italics/bold to this project - how do you recommend starting out doing so?

**Comment by ids1024** [comment]
@lengstrom I've already written a pull request (#122) but it has not been merged. It only works in `raw_display`, and the same funtionality should be added to `curses_display` if possible (it may not be), and it needs to be documented.

**Comment by wardi** [comment]
@ids1024 thanks, I've merged your PR
