### ISSUE TITLE
[BUG] `MainLoop.watch_pipe` is closed after the first callback  

### ISSUE THREAD

**Issue by exquo** [urwid/urwid#847]
##### Description:

`MainLoop.watch_pipe()` [documentation](https://urwid.org/reference/main_loop.html#urwid.MainLoop.watch_pipe) says:

> If the callback returns `False` then the watch will be removed from `event_loop` and the read end of the pipe will be closed.

However, since the following [commit](https://github.com/urwid/urwid/commit/1a5b18ca0b34876d6aa4937efca28751748d0f23#diff-350a967d4905ac920fdbd363bd511deffdfc3f52fe7920a384ad67ee8a13dd9b) the watch is removed when callback returns anything that *evaluates* to `False`. 

This breaks scripts using `watch_pipe()`: until the change above, a callback needed to explicitly `return False` to close the pipe. Now it gets closed after the first callback that did not explicitly `return True`. 

Is the motivation to enforce strict type-checking? (see also related commits: [[1]](https://github.com/urwid/urwid/commit/08946ebc620783ef45f99ea332b91d7874fcf23e#diff-350a967d4905ac920fdbd363bd511deffdfc3f52fe7920a384ad67ee8a13dd9bL236-R245), [[2]](https://github.com/urwid/urwid/commit/1300a69fde0bf31ad0eabe194ef3611e3057838d#diff-7f315191f02a076027d2d125d0290761ad02d49ef98638b87735d066b502e5de)). Perhaps it can be reconciled with the original behavior, thus avoiding a silent breaking change, and complying with the description in the docs?

##### Affected versions (if applicable)
- [x] `master` branch (specify commit): 9cee5b4
- [x] Latest stable version from `pypi`
- [x] Other (specify source): `2.6.x`

##### Steps to reproduce (if applicable)
Pass to `watch_pipe()` a callback that does not explicitly return `False`.

##### Expected/actual outcome
Expected: watch pipe stays open. Actual: watch pipe is closed.

**Comment by penguinolog** [comment]
Thank you for regression pointing. I'll fix it ASAP and add extra tests coverage to prevent regression re-introduce.

About typing: everything was smooth enough during python 2 period, but now we have a lot of implicit typing changes with fragile and sometimes broken behavior. The most complex pain is in the `Display` render part and `EventLoop`, where we are OS and site packages dependent and have the minimum real tests coverage.

**Comment by exquo** [comment]
👍 Appreciated! That was fast :)

Contending with externally controlled types must be a pain indeed. I'm sure you'll wrestle them down though!

Quick check: the signature

	def watch_pipe(self, callback: Callable[[bytes], bool]) -> int

has `bool` for the `callback`'s return type. Is that still okay, even though `callback` can return any type (most often - `None`)?

**Comment by penguinolog** [comment]
`def watch_pipe(self, callback: Callable[[bytes], bool | None])` is in the changed code. `None` should pass type checking.
Separating `Literal[False]` from `Any` is hard even for mypy, so we have to use reasonable types in signature (and `Literal` itself is not always correctly checked by IDE).

**Comment by exquo** [comment]
Ah geez I've only noticed the "context function" shown in GitHub's commit display: https://github.com/urwid/urwid/commit/210a79dcdd46b7398079fda488707c5a43c1cf44, and did not check the full diff. My mistake!

![gh_contxt](https://github.com/urwid/urwid/assets/62397152/86ba5e20-82a2-4e8a-bcbe-ad8e4ff7f9dd)

Makes sense using `bool | None`. I don't think there should be need for any other types in practice.
