### ISSUE TITLE
[BUG] Not receiving 'shift mouse press' events

### ISSUE THREAD

**Issue by aclindsa** [urwid/urwid#857]
##### Description:
Widgets are not receiving 'shift mouse press' events to their `mouse_event` methods in Linux.

##### Affected versions (if applicable)
- [x] `master` branch commit d95a31f1a0be6c650d5c96fed2676a0be5869d75
- [x] Latest stable version from `pypi` (I tested 2.6.8)
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
Run:
```
#!/usr/bin/env python

import logging
import urwid

class MyWidget(urwid.widget.Widget):
    _sizing = frozenset(['box'])

    def render(
        self,
        size: tuple[()] | tuple[int] | tuple[int, int],
        focus: bool = False,
    ) -> urwid.canvas.Canvas:
        return urwid.canvas.TextCanvas([bytes('x' * size[0], 'utf-8')] * size[1])

    def mouse_event(
        self,
        size: tuple[()] | tuple[int] | tuple[int, int],
        event: str,
        button: int,
        col: int,
        row: int,
        focus: bool,
    ) -> bool | None:
        logging.info(f'event={event} button={button}')

logging.basicConfig(filename='debug.log', encoding='utf-8', level=logging.INFO)
loop = urwid.MainLoop(MyWidget())
loop.run()
```

Then, while holding the Shift key, scroll the mouse wheel up.

##### Expected/actual outcome

I expect to see messages in `debug.log` like "event=shift mouse press button=4" (as described in http://urwid.org/manual/userinput.html#mouse-input). Instead, I don't see *any* messages when I scroll the mouse while holding Shift.

Scrolling in general does work in my environment. For example, I see 'event=ctrl mouse press button=4' when holding down the Ctrl key and scrolling up. I'm running this on Arch Linux with python 3.11.7, and I've tried it across several terminals (xterm, st, urxvt) with the same results.

**Comment by aclindsa** [comment]
I just enabled urwid's DEBUG logging and found some potentially helpful messages, so I'll share. When I scroll up while holding Ctrl inside my `st` terminal emulator, I see:
```
DEBUG:urwid.display._posix_raw_display.Screen.parse_input:Decoded codes: [('ctrl mouse press', 4, 41, 11)], raw codes: [27, 91, 60, 56, 48, 59, 52, 50, 59, 49, 50, 77]
DEBUG:urwid.event_loop.main_loop.MainLoop:Processing input: keys=[('ctrl mouse press', 4, 41, 11)]
```
But when I scroll up while holding Shift, I see instead:
```
DEBUG:urwid.display._posix_raw_display.Screen.parse_input:Decoded codes: ['ctrl y'], raw codes: [25]
DEBUG:urwid.event_loop.main_loop.MainLoop:Processing input: keys=['ctrl y']
```

When doing this in both `urxvt` and `xterm`, I do not see any such messages when holding Shift and scrolling (but I still see the same messages when holding Ctrl).

I'll note that I am able to use Shift + mouse scroll in other applications in my desktop to scroll horizontally, so I don't think I've accidentally done something silly to subvert my key/input mappings in X (but I'm happy to help rule out this possibility if you have ideas).

I'm also happy to help debug further, but would appreciate some guidance about what to try/where to look.

**Comment by penguinolog** [comment]
Originally `shift` handling was not implemented due to it's almost always intercepted for keys 1-3.

**Comment by aclindsa** [comment]
@penguinolog Thanks for looking into this so quickly!

Unfortunately, I pulled in your changes (verifying that `urwid.__version__` returns 2.6.9) and don't see any change in behavior.

Is there some way I can help debug what's going on for me in a way that's helpful?

**Comment by penguinolog** [comment]
You can test wia 'examples/input_test'. It provide decoded and raw input
data

Op wo 13 mrt 2024 15:58 schreef Aaron Lindsay ***@***.***>:

**Comment by aclindsa** [comment]
> You can test wia 'examples/input_test'. It provide decoded and raw input data

The output from examples/input_test.py matches what I saw with my own test program. This is what I see on `st`:

![2024-03-13-110724_1000x102_scrot](https://github.com/urwid/urwid/assets/362852/e33c0427-df69-4fb1-8904-9cdcccec4476)

`xterm` and `urxvt` show no output.

**Comment by aclindsa** [comment]
Hrm, okay, I do think I've found an option for `st` that allows me to see these events properly. I'm not sure about `xterm` and `urxvt`, but I assume they may be doing something similar... I'll dig in some more before bothering you further. Thanks!

**Comment by penguinolog** [comment]
I checked with `gnome-terminal` and `alacritty`.
Now also checked on `xterm` and `urxvt`: on both mouse input not received at all if `<shift>` pressed.
