### ISSUE TITLE
[BUG] ListBox wrapped in AttrMap is not scrollable with ScrollBar

### ISSUE THREAD

**Issue by rsekman** [urwid/urwid#878]
##### Description:

Wrapping a `ListBox` in an `AttrMap` should be transparent for operations such as adding a `ScrollBar`, but throws because the `AttrMap` is not realised to be scrollable.

##### Affected versions (if applicable)
- [x] `master` branch (7300acf3b1577efbacb5d54cb642aadf0849ef97)
- [x] Latest stable version from `pypi`
- [x] All versions since 2.5.0

##### Steps to reproduce (if applicable)
```python

import urwid as uw
w = uw.ScrollBar(uw.AttrMap(uw.ListBox([]), {}))
```

##### Expected/actual outcome
Expected behaviour: `w` can be scrolled as if it were not wrapped in an `AttrMap`.
Actual behaviour:
```
Traceback (most recent call last):
  File "/home/koyomi/Sandbox/test_attrmap.py", line 8, in <module>
    w = uw.ScrollBar(am)
        ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urwid/widget/scrollable.py", line 486, in __init__
    raise TypeError(f"Not a scrollable widget: {widget!r}")
TypeError: Not a scrollable widget: <AttrMap selectable box widget <ListBox selectable box widget> attr_map={}>
```

##### Cause

While `Scrollable` is aware of wrappers and descends into them to see if the original widgets are scrollable
 https://github.com/urwid/urwid/blob/7300acf3b1577efbacb5d54cb642aadf0849ef97/urwid/widget/scrollable.py#L615-L625
`ScrollBar` is not and does not
https://github.com/urwid/urwid/blob/7300acf3b1577efbacb5d54cb642aadf0849ef97/urwid/widget/scrollable.py#L484-L485

##### Fix

Make the check in `ScrollBar` analogous to the check in `Scrollable`.

**Comment by mfncooper** [comment]
Note that this bug also affects the ``tour.py`` example that ships with Urwid. This example thus provides a nice test case for the fix in #879, built right into the Urwid package. It would be good to verify that the examples work before releasing.
