### ISSUE TITLE
[Question]how can i input Chinese encoding into the Edit widget？

### ISSUE THREAD

**Issue by mLiXin** [urwid/urwid#882]
##### Description:
when i input Chinese encoding into the Edit widget，i got the ascii code in the widget，like this：

![image](https://github.com/urwid/urwid/assets/11740242/5b35c30d-b069-4dfc-bf16-4e2317ac5d9e)
![image](https://github.com/urwid/urwid/assets/11740242/e78e4773-cb5e-4319-983c-64d19afee915)

the question is : how can i input and show the Chinese encoding， not Ascii code?

**Comment by penguinolog** [comment]
Please try to run `input_test` example and validate which input is collected in binary and decoded.
You can check behavior with "curses" and "raw display"

**Comment by mLiXin** [comment]
curses：
![image](https://github.com/urwid/urwid/assets/11740242/645a8d30-a64d-4e3f-8850-468798f06e19)

raw：
![image](https://github.com/urwid/urwid/assets/11740242/a7a24abb-ccf4-4c87-a816-3474eabeac25)


> Please try to run `input_test` example and validate which input is collected in binary and decoded. You can check behavior with "curses" and "raw display"

**Comment by penguinolog** [comment]
Looks like decoding issue, decoding went different ways on curses and RAW - it can be even not 100% Unicode input.
I'm marking as bug.

**Comment by frac12** [comment]
I have tried to solve this problem, but I'm not sure whether my modifications are correct or if they will cause other issues. #934
