### ISSUE TITLE
How to scroll two listboxes together?

### ISSUE THREAD

**Issue by doctorcolossus** [urwid/urwid#885]
I have several `Column`s of `ListBox`es with `SimpleFocusListWalkers` which I wanted to keep synchronized in terms of scrolling and focus, and I am mainly asking for any advice about how to do that.

My idea was to register callbacks on each of the list walkers with `connect_signal()`, then when any one of them was modified, the callback would update the focus for all its sibling list walkers (I tried both using `.set_focus()` and directly setting `.focus_position`). In the for loop for siblings, I had to temporarily disconnect the signal before changing the focus, then reconnect it, to avoid infinite recursion. That seemed to run at least, but in the end syncing the focus seem to help with scrolling. So then I tried to query `.get_scrollpos()` of one of the `ListBox`es, but got the error:
```
line 302, in synchronize_focus
    print(list_box.get_scrollpos())
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urwid/widget/listbox.py", line 619, in get_scrollpos
    mid, top, _bottom = self.calculate_visible(self._rendered_size, focus)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urwid/widget/listbox.py", line 487, in calculate_visible
    self._set_focus_complete((maxcol, maxrow), focus)
  File "/usr/lib/python3.12/site-packages/urwid/widget/listbox.py", line 1085, in _set_focus_complete
    self.shift_focus((maxcol, maxrow), offset)
  File "/usr/lib/python3.12/site-packages/urwid/widget/listbox.py", line 1115, in shift_focus
    raise ListBoxError(f"Invalid offset_inset: {offset_inset!r}, only {tgt_rows!r} rows in target!")
urwid.widget.listbox.ListBoxError: Invalid offset_inset: -1, only 1 rows in target!
```

So if anybody understands that error,  an explanation could be helpful (it's saying "only 1 rows in target", but `len(list_box.body)` returns 49, so I don't understand).

But above all I would just like to achieve my goal of synchronized scrolling for multiple columns of lists in any way possible. Has anyone done this before, or does anyone have ideas about a simpler or better approach to locking several columns of lists to scroll in unison? This has turned out to be way more difficult than I anticipated and I am feeling frustrated and would be grateful for any ideas. Thank you.

**Comment by AnonymouX47** [comment]
Umm... Why not have a single `ListBox` containing `Columns`s ? :thinking:

**Comment by AnonymouX47** [comment]
You're welcome. :hugs:

It's totally okay, we all do miss what's right in front of us every now and then. Giving one another that little nudge when necessary is what matters. :smiley:

I'm really grateful for the support. Thank so much. :pray:
