### ISSUE TITLE
[BUG] interface changes make example/browser.py doesn't work as before

### ISSUE THREAD

**Issue by Xtinc** [urwid/urwid#892]
##### Description:
when running the browser.py in example directory, focused and selected lines doesn't show a distinct color as stated in https://urwid.org/examples/index.html.

##### Affected versions (if applicable)
- [x] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
1. get package from the most recent repo branch or stable release in pip.
2. then run /example/browser.py
3. current item is not highlighted, nor selected ones. 

##### Expected/actual outcome
expected:
![image](https://github.com/urwid/urwid/assets/39898895/77daaa09-886d-4183-a393-20e60a876fee)

actual
![image](https://github.com/urwid/urwid/assets/39898895/a267a9bc-016f-4a20-b7d6-e1a17c90bd0e)

##### Probable Reasons
a probable reason for this is the changes of AttrMap make code in function FlagFileWidget.update_w() works unexpectedly.
current code:
![image](https://github.com/urwid/urwid/assets/39898895/0b3c802d-674f-4207-a0a9-5c7524be1a2a)
if we change code to this:
![image](https://github.com/urwid/urwid/assets/39898895/ca4cea89-d666-40df-89ae-e1afca2cef53)
We get it work again

**Comment by penguinolog** [comment]
Can you make a PR with fix, please?

**Comment by Xtinc** [comment]
> Can you make a PR with fix, please?

Of course. I will make a pull request after I get the PR style of this repo soon.
