### ISSUE TITLE
High CPU load with AsyncioEventLoop

### ISSUE THREAD

**Issue by rndusr** [urwid/urwid#90]
My project's CPU load is between 8 and 9 % when it's doing absolutely nothing. I've found that setting `AsyncioEventLoop._idle_emulation_delay` from `1/256` to something like `1/20` reduces CPU load to around 1 %, and I don't notice any reduced responsiveness.

Also, `AsyncioEventLoop._we_started_event_loop` isn't used anywhere, so it can be removed?

**Comment by dcbaker** [comment]
Has there been any movement on this issue?

**Comment by tonycpsu** [comment]
7c8cd1e has been pushed as a workaround, as described in #86.
