### ISSUE TITLE
Creating a GridFlow with no children raises a warning

### ISSUE THREAD

**Issue by rsekman** [urwid/urwid#900]
##### Description:

Creating a `GridFlow` with no children raises a `GridFlowWarning` about the widget's size being smaller than its cell width.

##### Affected versions 
- [x] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [x] Other (specify source)

##### Steps to reproduce
```python
from urwid.widget import GridFlow
g = GridFlow([], 20, 1, 1, 'left')
```

##### Expected/actual outcome
Expected outcome: the widget is created with no no errors or warnings.

Actual outcome:
```
/usr/lib/python3.12/site-packages/urwid/widget/grid_flow.py:81: GridFlowWarning: Size is smaller than cell width (-1 < 20)
  super().__init__(self.generate_display_widget((self._cache_maxcol,)))
```

##### Cause

Unhandled edge case. In `GridFlow._get_maxcol`, the size of the widget is calculated as
https://github.com/urwid/urwid/blob/080e2873927fbcb7006ebd1c2e773fa2bcd0d1d4/urwid/widget/grid_flow.py#L432
If the `GridFlow`  has no children, we will get `maxcol = -h_sep`. This is incorrect; the maximum width of a `GridFlow` with no children should be `0`. Furthermore, in the case that the `GridFlow` has no children, it is not an error that it is less than one cell width wide. Both branches of `_get_maxcol` need to account for the edge case of no children.

**Comment by penguinolog** [comment]
Warning issue is a bit different, but I agree that it should be not produced if no children.
We have 2 places:
1. If size if set and it smaller than cell width - produce this warning.
2. Fixed calculation, which leads to negative `maxcol` on empty widget - bug.
