### ISSUE TITLE
urwid 2.6.15 fails with Python 3.12 : undefined symbol: PyUnicode_AS_UNICODE

### ISSUE THREAD

**Issue by wdormann** [urwid/urwid#937]
##### Description:
Upon updating urwid via pip on a system with Python 3.12 (via miniconda), urwid fails to load due to `undefined symbol: PyUnicode_AS_UNICODE

##### Affected versions (if applicable)
2.6.15 (via pip)

##### Steps to reproduce (if applicable)
On a system with Python 3.12, `pip install urwid`
In python, `import urwid`

##### Expected/actual outcome
No error

##### Actual outcome

```
$ python
Python 3.12.2 | packaged by Anaconda, Inc. | (main, Feb 27 2024, 17:35:02) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urwid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tapioca/miniconda/lib/python3.12/site-packages/urwid/__init__.py", line 30, in <module>
    from urwid.canvas import (
  File "/home/tapioca/miniconda/lib/python3.12/site-packages/urwid/canvas.py", line 30, in <module>
    from urwid.str_util import calc_text_pos, calc_width
ImportError: /home/tapioca/miniconda/lib/python3.12/site-packages/urwid/str_util.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyUnicode_AS_UNICODE
>>> 
```

**Comment by penguinolog** [comment]
Looks like you have precompiled internal module from previous versions.
Urwid 2.6 is not using `c` modules, so this error should be unreachable.

**Comment by penguinolog** [comment]
Solution: uninstall (ignoring dependency errors) and install again.

**Comment by wdormann** [comment]
Ah, thanks for the info!
The system did have a package called `urwid-mitmproxy` installed (via pip), and after explicit uninstallation of that, urwid works fine.  Sorry about the false alarm, so go ahead and close this one!
