### ISSUE TITLE
Cannot put a Terminal Widget in a ListBox Widget - Calculated cursor cords None but rendered cursor coords (x, y)

### ISSUE THREAD

**Issue by berney** [urwid/urwid#95]
If I create a Terminal widget that I decorate with a BoxAdapter widget and add it to a ListBox widget, when rendering the ListBox widget it throws an exception because the calculated cursor coordinates and the rendered coordinates do not match. The Terminal widget does not implement a get_cursor_coords() method, hence the calculated cursor coordinates are always None.

``` python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urwid
>>> vterm = urwid.Terminal(None)
>>> box_adapter = urwid.BoxAdapter(vterm, 20)
>>> list_box = urwid.ListBox(urwid.SimpleListWalker([box_adapter]))
>>> list_box.render((80,40))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Library/Python/2.7/site-packages/urwid/listbox.py", line 481, in render
    raise ListBoxError, "Focus Widget %r at position %r within listbox calculated cursor coords %r but rendered cursor coords %r!" %(focus_widget,focus_pos,cursor,c_cursor)
urwid.listbox.ListBoxError: Focus Widget <BoxAdapter selectable flow widget <Terminal selectable box widget> height=20> at position 0 within listbox calculated cursor coords None but rendered cursor coords (0, 0)!
>>> urwid.__version__
'1.3.0'
```

I tried to fix this by implementing a get_cursor_coords() method for urwid.Terminal, using it's term.term_cursor but this didn't work. 

``` python
def get_cursor_coords(self, size):
     if self.term:
         return self.term.term_cursor

urwid.Terminal.get_cursor_coords = get_cursor_coords
```

The first time it was called it seemed to return None still, later it would return (10,0) for instance, but ListBox's render would still see it as None. I don't understand enough to work out how to get this to work. I'd like use Terminal widgets to host the output of external commands so that it properly renders the output such as carriage returns. I'd like to have multiple terminals, one for each run of an external program, and I'd like the user to be able to scroll up and down in my Urwid application to see the output of each.

**Comment by d0c-s4vage** [comment]
@berney did you ever solve this?

**Comment by ulidtko** [comment]
Hey! As far as I can google, this is a pretty rare error, thrown from here: https://github.com/urwid/urwid/blob/66baad50e47aa5be60f65e04d77f63e889d3e37c/urwid/listbox.py#L450-L451 There's a [report from 2006][2006], one [from 2008][2008] and another from [2011][] -- and that's pretty much it.

In our team (where we use urwid for one app), I can see a **monkey patch** done to `listbox.py` around 2015. The patch exactly removes those two raising lines.

@d0c-s4vage perhaps you have a clear reproducer?.. I'd love to try and finally solve this (and so drop our monkey patch), but I'm lacking a repro example.

[•]: https://github.com/urwid/urwid/blob/66baad50e47aa5be60f65e04d77f63e889d3e37c/urwid/listbox.py#L450-L451
[2006]: http://lists.excess.org/pipermail/urwid/2006-March/000102.html
[2008]: https://bugs.launchpad.net/lyntin4/+bug/284485
[2011]: https://github.com/inducer/pudb/issues/22

**Comment by d0c-s4vage** [comment]
@ulidtko I do have a good example:

```python
container = urwid.ListBox([
    urwid.BoxAdapter(urwid.Terminal("bash -il"), 20),
])

loop = urwid.MainLoop(container)
loop.run()
```

**Comment by d0c-s4vage** [comment]
I think part of the problem is in Terminal, not ListBox. Terminal should not have a cursor unless it is in focus.

**Comment by ulidtko** [comment]
That's definitely the case. `Terminal` doesn't implement `get_cursor_coords` at all — but [according to the manual](http://urwid.org/manual/widgets.html#widget-displaying-the-cursor), it absolutely should.

I also see that some other critical pieces of terminal emulation logic are missing: like handling SIGCHLD. There's a circular dependency problem: to have properly functioning `Terminal`, you'd better pass it the `main_loop` (otherwise the pty pipes aren't properly polled), but to create a MainLoop requires already having the root widget created.

All in all, it looks like `vterm.py` needs more work. ListBox is just fine; but the Terminal is to blame.

**Comment by d0c-s4vage** [comment]
Thank you for checking it out! I may give fixing Terminal a go - if I make progress on it I'll submit a pull request.

**Comment by ulidtko** [comment]
Thanks to @d0c-s4vage PR, the Terminal-in-ListBox aspect should be fixed now.

I can still reproduce the same crash via #386 — thus that remains open.
