### ISSUE TITLE
factor out 2to3

### ISSUE THREAD

**Issue by bukzor** [urwid/urwid#98]
2to3 in urwid is causing me pain, here: https://bitbucket.org/ned/coveragepy/issue/347/coverage-pypy3-2to3-is-unacceptably-slow

Since 2to3 was invented, it's become a relatively simple matter to support both py2 and py3 with a single code base. Would you open to a patch that adds the `six` library as a dependency and factors out 2to3?

I've also had success with the `future` library, which makes your code base essentially python3 with some noop imports at the top, at the expense of some slight runtime under python2.

**Comment by penguinolog** [comment]
Master branch migrated to the python 3
